### ISSUE TITLE
Confused about conversion from Tensorflow chekpoint to Keras h5

### ISSUE THREAD

**Issue by felix-tracxpoint** [Microsoft/MMdnn#103]
Platform (like ubuntu 16.04/win10): Win10

Python version: 3.5

Source framework with version (like Tensorflow 1.4.1 with GPU): TF 1.5

Destination framework with version (like CNTK 2.3 with GPU): Keras 2.0

Pre-trained model path (webpath or webdisk path): 

Running scripts:

I am trying to do what is supposed to be a straightforward conversion from a TF checkpoint (with 3 files, meta, index, and data-00000-of-00001) to an h5 model I can use with Keras. 

But the documentation seems unclear as to what exactly are the steps. I cannot understand the meaning of all the -d,-n,-w, etc flags and keep getting errors.

Is there some detailed document I have missed, besides the instructions [here](https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/tensorflow/README.md)?

P.S.
I saw that there is a way to convert a pb file to a Keras snippet and then to an h5. But when I tried this with a pb model I have from TF it also failed.

**Comment by felix-tracxpoint** [comment]
Figured it out by now. Thanks.

**Comment by basque21** [comment]
could you provide some information of how did you figured out please?

**Comment by leemengtaiwan** [comment]
@felix-tracxpoint can you kindly provide more information about how you achieved converting TF checkpoints to Keras H5?

I'm stuck at converting Tensorflow MobileNetV2 to Keras

```
!mmconvert --srcFramework tensorflow \
    -in ./mobilenet/mobilenet_v2_1.0_160.ckpt.meta \
    -iw ./mobilenet/mobilenet_v2_1.0_160.ckpt \
    --dstFramework keras \
    --dstNodeName MMdnn_Output \
    --outputModel tf_to_keras.h5
```
