### ISSUE TITLE
Error in conversion from Tensorflow Model to CNTK Model

### ISSUE THREAD

**Issue by coolrishi2005** [Microsoft/MMdnn#11]
I have used the code at the link (https://github.com/aymericdamien/TensorFlow-Examples/blob/master/examples/4_Utils/save_restore_model.py) to create and store a model in tensorflow.

I am converting the saved tensorflow model to cntk using the steps mentioned in MMdnn. At the final step of convresion, i.e. while generating CNTK Model from CNTK Code Snippet, I am getting some error.

Following is the traceback:

(C:\Program Files\Anaconda3\envs\py35) MMdnn-master\mmdnn\conversion\cntk>python -m mmdnn.conversion.examples.cntk.imagenet_test -n cntkModel_3_5.py -w IRModel_3_5.npy --dump cntkModel_3_5.dnn
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\envs\py35\lib\runpy.py", line 184, in _run_mo
dule_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Anaconda3\envs\py35\lib\runpy.py", line 85, in _run_cod
e
    exec(code, run_globals)
  File "C:\Program Files\Anaconda3\envs\py35\lib\site-packages\mmdnn\conversion\
examples\cntk\imagenet_test.py", line 57, in <module>
    tester = TestCNTK()
  File "C:\Program Files\Anaconda3\envs\py35\lib\site-packages\mmdnn\conversion\
examples\cntk\imagenet_test.py", line 17, in __init__
    super(TestCNTK, self).__init__()
  File "C:\Program Files\Anaconda3\envs\py35\lib\site-packages\mmdnn\conversion\
examples\imagenet_test.py", line 104, in __init__
    self.MainModel = __import__(self.args.n)
  File "D:\Rishi\Machine Learning\CNTK\MMdnn-master\mmdnn\conversion\cntk\cntkMo
del_3_5.py", line 31
    Reshape_1       = cntk.reshape(Placeholder_1, shape = (,) name = 'Reshape_1'
)
                                                           ^
SyntaxError: invalid syntax

**Comment by kitstar** [comment]
Hi @coolrishi2005,
Thanks for helping test the converter. Tensorflow converter is in very initial state, any question and issue is welcome.

Fix some bugs and seems it works. Tensorflow -> IR command (step 1) is
```bash
python -m mmdnn.conversion._script.convertToIR -f tensorflow -d IRModel_3_5 -n /tmp/model.ckpt.meta -w /tmp/model.ckpt -node add
```

>Note: Please specify the output node of tensorflow model, which can help the converter trims useless nodes. like **-node add** in above command.

For this model, we can get the output node from codes:
![code](https://0qslhw.dm2304.livefilestore.com/y4m57Q8Nc7Vxw7JkU_YO7Vuu1_yxtBjo9euvoR1KpM5pwMSaO19CS6vuuGkysrK5ecgJokNp0z3NcprIT-ZrlcO7eB7HGcA-anx2SmH4JVIUrmy0T5DPtAEZ4HzlcVe8x5AZAH-ZWP1DnNcUARIp7fVS5AN-fiHmnW3xg456cssrusv0vL7BddKaCJiHxjMEGzIqVARxshJCqj3wxEloI9qCg?width=643&height=258&cropmode=none)

or from tensorboard
![tensorboard](https://npd9fa.dm2304.livefilestore.com/y4mX10KHM3zQEuFjlV55Mvh5PXmiYQ4Ohbu_vCh-TM4A6OZZ1syywSL64bBvdMvoIdTb2m5AS-AoabBb89PxrKqJKgtKHE_C9MtYAqIDe3MGQJddD39lgQnkrTiFx-huEWfWJ9eRz2yHKZnbXyM2_iAXjZXV0oDW88qTkDNzfXcs5LtI6vgHVm42KjZl5HItnWdNNizYYAlkx83qT6lV-EI7A?width=660&height=300&cropmode=none)

Thanks.

**Comment by coolrishi2005** [comment]
Thanks kitstar for the response. 
The model has been converted successfully now from tf -> cntk.
The issue was due to those useless nodes only, which got trimmed while generating IR Code from tf.

**Comment by mhajiaghayi** [comment]
hi there, i'm  trying to convert a transformer model that is trained with tf to cntk model. I get the following error. 

![image](https://user-images.githubusercontent.com/28695943/44430103-90319200-a54e-11e8-833c-03d151e32641.png)

**Comment by mhajiaghayi** [comment]
it seems it's not recognizing the attention layer. is there any way to get around that?

**Comment by mhajiaghayi** [comment]
hi namizz, how would you like me to send it to you? it's 800meg.

**Comment by namizzz** [comment]
Hi @mhajiaghayi , any free cloud storage is ok.

**Comment by mhajiaghayi** [comment]
hi @namizzz , you can find the model here https://1drv.ms/f/s!AqysHcfYW1hSgc57psU_Bh8MDND74A and I used the following script to convert it 

mmconvert -sf tensorflow -in checkpoints\model-0.meta -iw checkpoints\model-0 --dstNodeName output/fwside1/fwside1/fully_connected/Relu -df cntk -om cntk-model

**Comment by namizzz** [comment]
Hi @mhajiaghayi , MMdnn doesn't support RNN network now. Sorry,thanks!

**Comment by mhajiaghayi** [comment]
hi @namizzz, would you please look at this model located in https://1drv.ms/f/s!AqysHcfYW1hSgc8KG_BnQRrwT7vCJA? . This model doesn't use any RNN or attention layer. 
mmconvert -sf tensorflow -in checkpoints\model-0.meta -iw checkpoints\model-0 --dstNodeName output/fwside1/fwside1/fully_connected/Relu -df cntk -om cntk-model
