### ISSUE TITLE
Nasnet convert from Tensorflow to mxnet

### ISSUE THREAD

**Issue by caiqi** [Microsoft/MMdnn#110]
Platform (like ubuntu 16.04/win10):
 ubuntu 16.04
Python version:
python 3.5

I tried to convert nasnet from tensorflow to mxnet. In the first step Tf--> IR. The cmd is : 

`python -m mmdnn.conversion._script.convertToIR -f tensorflow -d nasnet_output_ir -n imagenet_nasnet-a_large.ckpt.meta --dstNodeName MMdnn_Output`

 it gives out the warnings: 

> Tensorflow has not supported operator [StridedSlice] with name [cell_stem_1/strided_slice].
> Tensorflow has not supported operator [Split] with name [cell_stem_0/split].
> Tensorflow has not supported operator [StridedSlice] with name [cell_0/strided_slice].
> Tensorflow has not supported operator [Split] with name [cell_stem_1/split].
> Tensorflow has not supported operator [Split] with name [cell_0/split].
> Tensorflow has not supported operator [Split] with name [cell_1/split].
> Tensorflow has not supported operator [Split] with name [cell_2/split].
> Tensorflow has not supported operator [Split] with name [cell_3/split].
> Tensorflow has not supported operator [Split] with name [cell_4/split].
> Tensorflow has not supported operator [StridedSlice] with name [cell_6/strided_slice].
> Tensorflow has not supported operator [Split] with name [cell_5/split].
> Tensorflow has not supported operator [Split] with name [reduction_cell_0/split].
> Tensorflow has not supported operator [Split] with name [cell_6/split].
> Tensorflow has not supported operator [Split] with name [cell_7/split].
> Tensorflow has not supported operator [Split] with name [cell_8/split].
> Tensorflow has not supported operator [Split] with name [cell_9/split].
> Tensorflow has not supported operator [Split] with name [cell_10/split].
> Tensorflow has not supported operator [StridedSlice] with name [cell_12/strided_slice].
> Tensorflow has not supported operator [Split] with name [cell_11/split].
> Tensorflow has not supported operator [Split] with name [reduction_cell_1/split].
> Tensorflow has not supported operator [Split] with name [cell_12/split].
> Tensorflow has not supported operator [Split] with name [cell_13/split].
> Tensorflow has not supported operator [Split] with name [cell_14/split].
> Tensorflow has not supported operator [Split] with name [cell_15/split].
> Tensorflow has not supported operator [Split] with name [cell_16/split].
> Tensorflow has not supported operator [Split] with name [cell_17/split].
> Tensorflow has not supported operator [BiasAdd] with name [final_layer/FC/BiasAdd].
. 

In the second step from IR to mxnet, 
`python -m mmdnn.conversion._script.IRToCode -f mxnet --IRModelPath nasnet_output_ir.pb --dstModelPath mxnet_nasnet.py --IRWeightPath nasnet_output_ir.npy -dw mxnet_nasnet-0000.params`,
it gives following warnings and errors:

> Warning: Graph Construct a self-loop node cell_stem_1/strided_slice. Ignored.
> Warning: Graph Construct a self-loop node cell_stem_0/split. Ignored.
> Warning: Graph Construct a self-loop node cell_stem_0/split. Ignored.
> Warning: Graph Construct a self-loop node cell_stem_0/split. Ignored.
> Warning: Graph Construct a self-loop node cell_stem_0/split. Ignored.
> Warning: Graph Construct a self-loop node cell_0/strided_slice. Ignored.
> Warning: Graph Construct a self-loop node cell_stem_1/split. Ignored.
> Warning: Graph Construct a self-loop node cell_stem_1/split. Ignored.
> Warning: Graph Construct a self-loop node cell_stem_1/split. Ignored.
> Warning: Graph Construct a self-loop node cell_stem_1/split. Ignored.
> Warning: Graph Construct a self-loop node cell_0/split. Ignored.
> Warning: Graph Construct a self-loop node cell_0/split. Ignored.
> Warning: Graph Construct a self-loop node cell_0/split. Ignored.
> Warning: Graph Construct a self-loop node cell_0/split. Ignored.
> Warning: Graph Construct a self-loop node cell_1/split. Ignored.
> Warning: Graph Construct a self-loop node cell_1/split. Ignored.
> Warning: Graph Construct a self-loop node cell_1/split. Ignored.
> Warning: Graph Construct a self-loop node cell_1/split. Ignored.
> Warning: Graph Construct a self-loop node cell_2/split. Ignored.
> Warning: Graph Construct a self-loop node cell_2/split. Ignored.
> Warning: Graph Construct a self-loop node cell_2/split. Ignored.
> Warning: Graph Construct a self-loop node cell_2/split. Ignored.
> Warning: Graph Construct a self-loop node cell_3/split. Ignored.
> Warning: Graph Construct a self-loop node cell_3/split. Ignored.
> Warning: Graph Construct a self-loop node cell_3/split. Ignored.
> Warning: Graph Construct a self-loop node cell_3/split. Ignored.
> Warning: Graph Construct a self-loop node cell_4/split. Ignored.
> Warning: Graph Construct a self-loop node cell_4/split. Ignored.
> Warning: Graph Construct a self-loop node cell_4/split. Ignored.
> Warning: Graph Construct a self-loop node cell_4/split. Ignored.
> Warning: Graph Construct a self-loop node cell_6/strided_slice. Ignored.
> Warning: Graph Construct a self-loop node cell_5/split. Ignored.
> Warning: Graph Construct a self-loop node cell_5/split. Ignored.
> Warning: Graph Construct a self-loop node cell_5/split. Ignored.
> Warning: Graph Construct a self-loop node cell_5/split. Ignored.
> Warning: Graph Construct a self-loop node reduction_cell_0/split. Ignored.
> Warning: Graph Construct a self-loop node reduction_cell_0/split. Ignored.
> Warning: Graph Construct a self-loop node reduction_cell_0/split. Ignored.
> Warning: Graph Construct a self-loop node reduction_cell_0/split. Ignored.
> Warning: Graph Construct a self-loop node cell_6/split. Ignored.
> Warning: Graph Construct a self-loop node cell_6/split. Ignored.
> Warning: Graph Construct a self-loop node cell_6/split. Ignored.
> Warning: Graph Construct a self-loop node cell_6/split. Ignored.
> Warning: Graph Construct a self-loop node cell_7/split. Ignored.
> Warning: Graph Construct a self-loop node cell_7/split. Ignored.
> Warning: Graph Construct a self-loop node cell_7/split. Ignored.
> Warning: Graph Construct a self-loop node cell_7/split. Ignored.
> Warning: Graph Construct a self-loop node cell_8/split. Ignored.
> Warning: Graph Construct a self-loop node cell_8/split. Ignored.
> Warning: Graph Construct a self-loop node cell_8/split. Ignored.
> Warning: Graph Construct a self-loop node cell_8/split. Ignored.
> Warning: Graph Construct a self-loop node cell_9/split. Ignored.
> Warning: Graph Construct a self-loop node cell_9/split. Ignored.
> Warning: Graph Construct a self-loop node cell_9/split. Ignored.
> Warning: Graph Construct a self-loop node cell_9/split. Ignored.
> Warning: Graph Construct a self-loop node cell_10/split. Ignored.
> Warning: Graph Construct a self-loop node cell_10/split. Ignored.
> Warning: Graph Construct a self-loop node cell_10/split. Ignored.
> Warning: Graph Construct a self-loop node cell_10/split. Ignored.
> Warning: Graph Construct a self-loop node cell_12/strided_slice. Ignored.
> Warning: Graph Construct a self-loop node cell_11/split. Ignored.
> Warning: Graph Construct a self-loop node cell_11/split. Ignored.
> Warning: Graph Construct a self-loop node cell_11/split. Ignored.
> Warning: Graph Construct a self-loop node cell_11/split. Ignored.
> Warning: Graph Construct a self-loop node reduction_cell_1/split. Ignored.
> Warning: Graph Construct a self-loop node reduction_cell_1/split. Ignored.
> Warning: Graph Construct a self-loop node reduction_cell_1/split. Ignored.
> Warning: Graph Construct a self-loop node reduction_cell_1/split. Ignored.
> Warning: Graph Construct a self-loop node cell_12/split. Ignored.
> Warning: Graph Construct a self-loop node cell_12/split. Ignored.
> Warning: Graph Construct a self-loop node cell_12/split. Ignored.
> Warning: Graph Construct a self-loop node cell_12/split. Ignored.
> Warning: Graph Construct a self-loop node cell_13/split. Ignored.
> Warning: Graph Construct a self-loop node cell_13/split. Ignored.
> Warning: Graph Construct a self-loop node cell_13/split. Ignored.
> Warning: Graph Construct a self-loop node cell_13/split. Ignored.
> Warning: Graph Construct a self-loop node cell_14/split. Ignored.
> Warning: Graph Construct a self-loop node cell_14/split. Ignored.
> Warning: Graph Construct a self-loop node cell_14/split. Ignored.
> Warning: Graph Construct a self-loop node cell_14/split. Ignored.
> Warning: Graph Construct a self-loop node cell_15/split. Ignored.
> Warning: Graph Construct a self-loop node cell_15/split. Ignored.
> Warning: Graph Construct a self-loop node cell_15/split. Ignored.
> Warning: Graph Construct a self-loop node cell_15/split. Ignored.
> Warning: Graph Construct a self-loop node cell_16/split. Ignored.
> Warning: Graph Construct a self-loop node cell_16/split. Ignored.
> Warning: Graph Construct a self-loop node cell_16/split. Ignored.
> Warning: Graph Construct a self-loop node cell_16/split. Ignored.
> Warning: Graph Construct a self-loop node cell_17/split. Ignored.
> Warning: Graph Construct a self-loop node cell_17/split. Ignored.
> Warning: Graph Construct a self-loop node cell_17/split. Ignored.
> Warning: Graph Construct a self-loop node cell_17/split. Ignored.
> Warning: Graph Construct a self-loop node final_layer/FC/BiasAdd. Ignored.
> Detect input layer [input] using infer batch size, set it as default value [1]
> Traceback (most recent call last):
>   File "/home/XXX/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/XXX/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/XXX/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/_script/IRToCode.py", line 112, in <module>
>     _main()
>   File "/home/XXX/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/_script/IRToCode.py", line 107, in _main
>     ret = _convert(args)
>   File "/home/XXX/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/_script/IRToCode.py", line 55, in _convert
>     emitter.run(args.dstModelPath, args.dstWeightPath, args.phase)
>   File "/home/XXX/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 21, in run
>     self.save_code(dstNetworkPath, phase)
>   File "/home/XXX/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 53, in save_code
>     code = self.gen_code(phase)
>   File "/home/XXX/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/mxnet/mxnet_emitter.py", line 96, in gen_code
>     line = func(current_node)
>   File "/home/XXX/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/mxnet/mxnet_emitter.py", line 552, in emit_Pool
>     self.parent_variable_name(IR_node),
>   File "/home/XXX/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 41, in parent_variable_name
>     return self.IR_graph.get_parent(IR_node.name, path).real_variable_name
>   File "/home/XXX/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/common/DataStructure/graph.py", line 86, in get_parent
>     current_node = self.get_node(parent_name)
>   File "/home/XXX/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/common/DataStructure/graph.py", line 62, in get_node
>     raise IOError("Graph doesn't have node [%s]." % name)
> OSError: Graph doesn't have node [data].

Could you please give some advices on how to solve it? Thanks!

**Comment by kitstar** [comment]
Hi @caiqi nasnet is under developing, we will ping you if there is any progress. Thanks!

**Comment by hwpengms** [comment]
same problem, when will the new feature release?

**Comment by kitstar** [comment]
Hi @caiqi and @hwpengms , not quite sure if mxnet supports all the related operators. I will figure it out but it won't be soon. Thanks.

**Comment by rxdhr** [comment]
@kitstar , I transformed the NasNet code from tensorflow to mxnet and found that most ops are supported in mxnet. But in NasNet a dropout ratio changes with respect to `tf.train.get_or_create_global_step()` which is not available in mxnet. So I wonder whether it would be possible to automatically transform the saved checkpoint. Do you have some suggestions on transform saved checkpoint? Thanks.

**Comment by kitstar** [comment]
Hi @rxdhr , I think we need to write the tensorflow stridedslice and split layer in TensorFlow Parser firstly.

**Comment by hwpengms** [comment]
Hi @kitstar , I am writing rename_strideslice, rename_split has been done. Share with you when finished.

**Comment by kitstar** [comment]
Hi @rxdhr @caiqi @hwpengms . Tensorflow Nasnet -> tf/pytorch/mxnet test passed. please try newest code. Thanks.

**Comment by hwpengms** [comment]
Great work! @kitstar
