### ISSUE TITLE
CaffeEmitter has not supported operator [Sequential]

### ISSUE THREAD

**Issue by lamdawr** [Microsoft/MMdnn#112]
Platform (like ubuntu 16.04/win10): ubuntu 14.04

Python version: 3.6

Source framework with version (like Tensorflow 1.4.1 with GPU): Keras 2.1.3

Destination framework with version (like CNTK 2.3 with GPU): Caffe

Pre-trained model path (webpath or webdisk path):

Running scripts:

I am trying to convert a VGG keras model to Caffe model. I had no issue converting keras to IR model but when trying to create the target network code .py and target weights .npy with caffe, I get the following : CaffeEmitter has not supported operator [sequential]. But I did get a .py and npy weights file after that.

**Comment by kitstar** [comment]
Hi @lamdawr , in our testing, vgg model from keras offical application doesn't have sequential layer. Is it your own model? Thanks.
