### ISSUE TITLE
How to support split op in Tensorflow?

### ISSUE THREAD

**Issue by guohengkai** [Microsoft/MMdnn#115]
Hi,

In the current version, one layer in IR has only one output. But for split op, it has multiple outputs (split, split:1, split:2, ...). So do you have any ideas about it?

Thanks.

**Comment by kitstar** [comment]
Hi @guohengkai, in my opinion, it will give code like
```python
sp_1, sp_2, ..., sp_n = tf.split(xxxx, name='sp')     # the sp_x is generated by the operator's name
```

And it may need some effort on tensorflow_graph representation. Thanks.

**Comment by kitstar** [comment]
Yes, but it may take some time to support it. Ping you if there is any progress.

**Comment by guohengkai** [comment]
@kitstar OK, thanks!
