### ISSUE TITLE
Has CNTK TO IR been available?

### ISSUE THREAD

**Issue by xbgydxlq** [Microsoft/MMdnn#116]
I need convert a CNTK model to Caffe model, so I try to convert CNTK to IR first. But when I run 

" python -m mmdnn.conversion._script.convertToIR --srcFramework cntk --network ... --dstPath ...", there is an error:

Cntk Parser has not supported operator [Convolution2D] with name [Block2107].
Layer:  <cntk.ops.functions.Function; proxy of <Swig Object of type 'std::shared
_ptr< CNTK::Function > *' at 0x00000044AF4DF9C0> >
Parameters:  (<cntk.ops.variables.Parameter; proxy of <Swig Object of type 'CNTK
::Parameter *' at 0x000000449B848E70> >, <cntk.ops.variables.Parameter; proxy of
 <Swig Object of type 'CNTK::Parameter *' at 0x00000044AF4DF030> >)
Attributes:  {}
<cntk.ops.variables.Variable; proxy of <Swig Object of type '::CNTK::Variable *'
 at 0x000000449B848E70> >
<cntk.ops.variables.Variable; proxy of <Swig Object of type '::CNTK::Variable *'
 at 0x00000044AF4DF030> >
<cntk.ops.variables.Variable; proxy of <Swig Object of type '::CNTK::Variable *'
 at 0x00000044AF4DF060> >
Traceback (most recent call last):
  File "C:\Users\qiluan\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 19
3, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\qiluan\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 85
, in _run_code
    exec(code, run_globals)
  File "C:\Users\qiluan\AppData\Local\Continuum\Anaconda3\lib\site-packages\mmdn
n\conversion\_script\convertToIR.py", line 148, in <module>
    _main()
  File "C:\Users\qiluan\AppData\Local\Continuum\Anaconda3\lib\site-packages\mmdn
n\conversion\_script\convertToIR.py", line 143, in _main
    ret = _convert(args)
  File "C:\Users\qiluan\AppData\Local\Continuum\Anaconda3\lib\site-packages\mmdn
n\conversion\_script\convertToIR.py", line 80, in _convert
    parser.run(args.dstPath)
  File "C:\Users\qiluan\AppData\Local\Continuum\Anaconda3\lib\site-packages\mmdn
n\conversion\common\DataStructure\parser.py", line 22, in run
    self.gen_IR()
  File "C:\Users\qiluan\AppData\Local\Continuum\Anaconda3\lib\site-packages\mmdn
n\conversion\cntk\cntk_parser.py", line 80, in gen_IR
    self.rename_UNKNOWN(current_node)
  File "C:\Users\qiluan\AppData\Local\Continuum\Anaconda3\lib\site-packages\mmdn
n\conversion\cntk\cntk_parser.py", line 132, in rename_UNKNOWN
    assert False
AssertionError

Can you tell me whether the error is caused by the not-finished code or my code is wrong.
Thanks!!!

**Comment by kitstar** [comment]
Hi @xbgydxlq , we tested the original CNTK pre-trained model resnet and inception_v3 and it works. But it can't work for caffe-converted pre-trained model.

I searched the related issue and get [this issue](https://github.com/Microsoft/CNTK/issues/2200). I will try to implement it and see if it works. Thanks.

**Comment by xbgydxlq** [comment]
@kitstar, thanks for your quick reply!

Do you mean the model I used is converted from caffe model?

**Comment by kitstar** [comment]
Yes it is.
