### ISSUE TITLE
From Caffe to Pytorch, PReLU is not support ?

### ISSUE THREAD

**Issue by waynheng** [Microsoft/MMdnn#124]
Pre-trained model path (webpath or webdisk path):
https://drive.google.com/file/d/0B_geeR2lTMegb2F6dmlmOXhWaVk/view

I want converts layers before fc5 from caffemodel, it seems the PReLU is not support yet. 

![image](https://user-images.githubusercontent.com/24382093/37755428-6e935e8e-2de0-11e8-80f9-bd98cbabd8c2.png)

**Comment by namizzz** [comment]
Hi @waynheng  could you share your prototxt for us ? Thanks.
