### ISSUE TITLE
How to convert a Amazon Sagemaker model into a Tensorflow model

### ISSUE THREAD

**Issue by vasantivmahajan** [Microsoft/MMdnn#138]
I have trained and saved a model using Amazon SageMaker and I need to convert it into a Tensorflow model. Is there a way that this can be achieved?

**Comment by kitstar** [comment]
Not familiar with Amazon SageMaker. Could you provide some for investigation? Thanks.

**Comment by vasantivmahajan** [comment]
You can access the model from here https://drive.google.com/drive/folders/1rZiN25hxCtzr4vdyaPK9LFf8B63tQd51?usp=sharing

**Comment by kitstar** [comment]
Hi @vasantivmahajan , your model is MxNet model, you can follow the mxnet -> tensorflow examples to do it, with model file (mx-mod-symbol.json and mx-mod-0000.params). Please ping us if there is any error. Thanks.
