### ISSUE TITLE
Error while converting from IR to CNTK (leaky_relu and upsampling2d)

### ISSUE THREAD

**Issue by almeida29** [Microsoft/MMdnn#143]
Platform : win 10

Python version: 3.5.2

Source framework with version : keras with tensorflow 1.7.0 on CPU

Destination framework with version : CNTK 2.4 on CPU

Running scripts:
**1. Convert the pre-trained model files to intermediate representation**
$ mmtoir -f keras -w yolo.h5 -o yolov3

**2. Convert the IR files to CNTK models**
$ mmtocode -f cntk -d converted_cntk.py -n yolov3.pb -w yolov3.npy

Description:
Converted trained model yolo.h5 from Keras -> IR.
Got an error while converting from IR->CNTK.
The error while running the second command is at link: https://pastebin.com/pxBVmj10

**Comment by kitstar** [comment]
Hi @almeida29 , does your keras yolo model come from YAD2K?

**Comment by almeida29** [comment]
Hi kitstar

1. We took a pretrained model from Darknet: https://pjreddie.com/darknet/yolo/
2. We used the following project to convert yolov3 to keras: https://github.com/qqwweee/keras-yolo3
wget https://pjreddie.com/media/files/yolov3.weights
python convert.py yolov3.cfg yolov3.weights model_data/yolo.h5

Thanks.

**Comment by kitstar** [comment]
Thanks @almeida29. We will try it. And did you test the inference correction after conversion?

**Comment by almeida29** [comment]
Hi Kitstar
We didn't do inference correction as we were trying to get the model in cntk and then run the inference in the cntk framework. 
Thanks.

**Comment by namizzz** [comment]
Hi @almeida29 , please check the newest code. leaky_relu and upsampling2d is added to CNTK emitter. Here is [readme](https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/darknet/README.md). Thanks!

**Comment by kitstar** [comment]
Hi, please try newest code
```python
pip install -U git+https://github.com/Microsoft/MMdnn.git@master
```

Darknet related code hasn't been merged to offical release.

**Comment by kitstar** [comment]
Hi @almeida29 .  Please try newest code. A small fix on py3 darknet parser. Thanks.

**Comment by almeida29** [comment]
Thanks Kitstar.
The above command worked for me. The next step was to convert **IR to CNTK**

**Comment by kitstar** [comment]
@almeida29   Have you install cntk in your python3?

**Comment by almeida29** [comment]
Thanks @kitstar, I installed cntk in python3 and now am getting the following error while trying to save the cntk model:

**(3point6) C:\Users\TestSystem>mmtomodel -f cntk -in cntk_yolov3_converted -iw darknet_yolov3.npy -o cntk_yolo_v3.dnn**
Selected CPU as the process wide default device.
c:\users\TestSystem\appdata\local\programs\python\python36\lib\site-packages\cntk\core.py:82: RuntimeWarning: data is not C contiguous; rearrange your data/computation to avoid costly data conversions
  RuntimeWarning)
Traceback (most recent call last):
  File "C:\Users\TestSystem\AppData\Local\Programs\Python\Python36\Scripts\mmtomodel-script.py", line 11, in <module>
    load_entry_point('mmdnn==0.1.4', 'console_scripts', 'mmtomodel')()
  File "c:\users\TestSystem\appdata\local\programs\python\python36\lib\site-packages\mmdnn\conversion\_script\dump_code.py", line 67, in _main
    ret = dump_code(args.framework, args.inputNetwork, args.inputWeight, args.outputModel)
  File "c:\users\TestSystem\appdata\local\programs\python\python36\lib\site-packages\mmdnn\conversion\_script\dump_code.py", line 28, in dump_code
    save_model(MainModel, network_filepath, weight_filepath, dump_filepath)
  File "c:\users\TestSystem\appdata\local\programs\python\python36\lib\site-packages\mmdnn\conversion\cntk\saver.py", line 3, in save_model
    model.save(dump_filepath)
AttributeError: 'tuple' object has no attribute 'save'

**Comment by namizzz** [comment]
Hi @almeida29  
The outputs consist of there results in shape of ((1, 13, 13, 255), (1, 26, 26, 255), (1, 52, 52, 255), so it's a tuple.

You need to follow these steps:
mmtocode -f cntk -n xxx.pb -w xxx.npy -d cntk_yolov3_converted.py

python -m mmdnn.conversion.examples.cntk.imagenet_test -n cntk_yolov3_converted.py -w xxx.npy -i mmdnn/conversion/examples/data/dog.jpg -s darknet -p yolov3 --detect test

You can save the outputs file(*.npy) as the [README](https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/darknet/README.md)

**Comment by almeida29** [comment]
Hi @namizzz, I am looking to get the CNTK model as I eventually want to convert it to an ONNX model.
Is there a way to use mmtomodel script to do the conversion to CNTK .dnn model?

**Comment by kitstar** [comment]
Hi @almeida29 , you can submit this issue to CNTK repo to see if there is a solution. Or we are working on ONNX Emitter and ping you if it is done. Thanks.

**Comment by whatlearn** [comment]
hi @almeida29，  I have the same problem as you. Have you succeeded in converting. dnn?

**Comment by elevir** [comment]
@whatlearn if it is still actual. In file with path which is printed in error such as "File "D:\Users\Paul\AppData\Local\Programs\Python\Python36\lib\site-packages\mmdnn\conversion\examples\cntk\imagenet_test.py"" try to change line 53 from self.model.save(path) to C.combine(self.model).save(path). It has solved my problem (just for yolov3 model).

**Comment by whatlearn** [comment]
@elevir  Thank you, but I want convert to YOLOv2, I will try your method
