### ISSUE TITLE
TensorflowEmitter has not supported operator [sum].

### ISSUE THREAD

**Issue by dhaase-de** [Microsoft/MMdnn#15]
This happened to me when converting a Caffe ResNet model to TensorFlow. I used Python 3 and `MMdnn-0.1.1`, installed via `pip`.

**Comment by kitstar** [comment]
Hi @dhaase-de , I will add the Sum in Tensorflow, pull request is welcome. Thanks.

**Comment by dhaase-de** [comment]
With your suggested edit, the export finishes without errors. I don't have the time now to verify the exported TensorFlow net, but the code looks good and it loads without errors in Python 3. Thanks!
