### ISSUE TITLE
PIP only has 0.1.5 version, which isn't on github releases page

### ISSUE THREAD

**Issue by danzel** [Microsoft/MMdnn#158]
The python repository only has a `0.1.5` version of MMdnn.
https://pypi.org/project/mmdnn/#history

But checking the github releases for MMdnn, the latest is `0.1.4`
https://github.com/Microsoft/MMdnn/releases

Is this correct? It seems a bit strange there is no version history on pypi.

**Comment by kitstar** [comment]
Hi @danzel , it is correct. Please use 0.1.5 version of MMdnn, and will release the binary on Pypi in the future.

**Comment by danzel** [comment]
Thanks!
