### ISSUE TITLE
wrong tool is mentioned in doc

### ISSUE THREAD

**Issue by aakbar5** [Microsoft/MMdnn#169]
`mmtoir` is mentioned under *Convert models from IR to PyTorch code snippet and weights* heading to convert IR into Code whereas it should be `mmtocode`.

wrong:
```
$ mmtoir -f pytorch -n inception_v3.pb --IRWeightPath inception_v3.npy --dstModelPath pytorch_inception_v3.py -dw pytorch_inception_v3.npy
```

correct:
```
$ mmtocode -f pytorch -n inception_v3.pb --IRWeightPath inception_v3.npy --dstModelPath pytorch_inception_v3.py -dw pytorch_inception_v3.npy
```

**Comment by JiahaoYao** [comment]
I have created a pull request to change it, and this issue is to be closed.
