### ISSUE TITLE
caffe to onnx - data layer attribute lacks dtype

### ISSUE THREAD

**Issue by wzhgba** [Microsoft/MMdnn#190]
I use mmdnn to convert caffe (build from master branch on linux and python 3.5) model to onnx format with latest mmdnn master branch code, and meet error.

The 1st step caffe->IR is successful, however in the 2nd step IR->onnx error happens that data layer contains no "dtype" attribute.

Seeking for help. Thanks!

**Comment by zhantong** [comment]
The Caffe -> ONNX convert is under active developing now, we currently haven't tested on that yet, we'll support that soon.

Can you provide some detailed error info? we have just fixed the DataInput layer no dtype attribute error, could you have a try?

**Comment by wzhgba** [comment]
Really thank you for quick response!

The DataInput dtype error is fixed in the latest master branch. Another error happens that conv layer IR_node.get_attr('dilations') fails.

Since the caffe->onnx path still needs time to develop, I'll use caffe->keras->onnx for my short-term plan.

**Comment by zhantong** [comment]
Yeah we are just fixing the no dilations attribute issue.

Will let you know as soon as we fixed that.

**Comment by zhantong** [comment]
Hi @wzhgba , we have fixed some issues and now MMdnn supports Caffe -> ONNX convert with limited operators (#194 ).

Please let us know if it solves your problems.

**Comment by wzhgba** [comment]
It works for my case now. Thanks a lot!
