### ISSUE TITLE
Unable to generate PyTorch model from code snippet file and weight file

### ISSUE THREAD

**Issue by lizilongcn** [Microsoft/MMdnn#205]
https://github.com/Microsoft/MMdnn/blob/80ca95c3b7cabb58b1d6d9d54b252446839ceb54/mmdnn/conversion/_script/dump_code.py#L39

Hi, thanks for your work.

When I try to generate pytorch model, the code raises an error showing that `invalid choice: 'pytorch' `. The problem may be caused by the choices  in `dump_code.py L39`.

**Comment by liangfu** [comment]
I think that should definitely works, because the parser [in this line](https://github.com/Microsoft/MMdnn/blob/80ca95c3b7cabb58b1d6d9d54b252446839ceb54/mmdnn/conversion/_script/dump_code.py#L20) identify `pytorch` as `pytorch`, not `torch`.
