### ISSUE TITLE
mxnet to IR Error

### ISSUE THREAD

**Issue by honghuCode** [Microsoft/MMdnn#223]
I have a face Project in https://github.com/honghuCode/mobileFacenet-ncnn .Now I want to implement it by caffe.So I want to convert mxnet project to caffe.

![image](https://user-images.githubusercontent.com/14934309/40818720-17e02fb2-658b-11e8-8262-fd8f19eca637.png)

this is my mxnet network architecture
[model-symbol.txt](https://github.com/Microsoft/MMdnn/files/2060840/model-symbol.txt)

**Comment by namizzz** [comment]
Hi @honghuCode , I have checked the[ weight file](https://github.com/honghuCode/mobileFacenet-ncnn/blob/master/model-y1/model-y1-test2/model-0000.params). I only find 'pre_fc1_bias' in the parameter start with 'pre_fc1'. So when it get the 'pre_fc1_weight', there is a error.

**Comment by honghuCode** [comment]
I have no idea about 'pre_fc1_weight'' ,But the mxnet network can work normly,and there is a project to transfer mxnet weight to [ncnn](https://github.com/Tencent/ncnn/tree/master/tools/mxnet) https://github.com/Tencent/ncnn/tree/master/tools/mxnet

**Comment by namizzz** [comment]
Hi @honghuCode , I think it's because the weight variable of FullyConnected 'pre_fc1' is named manually as something else.  You can check the code and fix it in mxnet_parser
```python
weight = self.weight_data.get(name_of_weight).asnumpy().transpose((1, 0))
```
and see if it works? Thanks.

**Comment by namizzz** [comment]
Hi @honghuCode , there is no error shown here. Can you send it again?

**Comment by honghuCode** [comment]
@namizzz ,sorry,I did not upload the error page,now I upload it.

**Comment by namizzz** [comment]
Hi @honghuCode ,
You only provide network structure in command, so there is no weight_data .Try to use
```cmd
mmtoir -f mxnet -n model-y1-softmax-symbol.json -w -d mfaceNet --inputShape 3 112 112 -w model-0000.params
```
and see if it works? Thanks
