### ISSUE TITLE
mobilenet_v1 tensorflow to caffe: Empty result files

### ISSUE THREAD

**Issue by svebert** [Microsoft/MMdnn#225]
Platform (like ubuntu 16.04/win10):
Win 10
Python version:
Python 3.5.4
Source framework with version (like Tensorflow 1.4.1 with GPU):
TF 1.8.0 with GPU
Destination framework with version (like CNTK 2.3 with GPU):
2.5.1
Pre-trained model path (webpath or webdisk path):
model.ckpt.meta: https://ufile.io/vssw2
model.ckpt.index: https://ufile.io/2q0ge
model.ckpt.data-00000-of-00001: https://ufile.io/97p1v
model.ckpt is a mobilenet_v1 model build and pre-trained by the tensorflow object detection api. 
Running scripts:
`mmconvert -sf tensorflow -in model.ckpt-24724.meta -iw model.ckpt-24724 -df caffe -om mobilenet_v1_caffe --inputShape 3 224 224 --dstNodeName Squeeze`

When I run the script from cmd
`mmconvert -sf tensorflow -in model.ckpt-24724.meta -iw model.ckpt-24724 -df caffe -om mobilenet_v1_caffe --inputShape 3 224 224 --dstNodeName Squeeze
`
I get the following output:

> Parse file [model.ckpt-24724.meta] with binary format successfully.
> Tensorflow model file [model.ckpt-24724.meta] loaded successfully.
> Tensorflow checkpoint file [model.ckpt-24724] loaded successfully. [587] variables loaded.
> Tensorflow has not supported operator [Iterator] with name [Iterator].
> Tensorflow has not supported operator [NoOp] with name [IteratorGetNext:8].
> Tensorflow has not supported operator [IteratorGetNext] with name [IteratorGetNext].
> Tensorflow has not supported operator [ExpandDims] with name [ExpandDims].
> Tensorflow has not supported operator [Cast] with name [ToFloat].
> IR network structure is saved as [9b2b46ad93cb4c0bbc1b54a49bad2815.json].
> IR network structure is saved as [9b2b46ad93cb4c0bbc1b54a49bad2815.pb].
> IR weights are saved as [9b2b46ad93cb4c0bbc1b54a49bad2815.npy].
> Parse file [9b2b46ad93cb4c0bbc1b54a49bad2815.pb] with binary format successfully.
> Warning: Graph Construct a self-loop node ToFloat. Ignored.
> Target network code snippet is saved as [9b2b46ad93cb4c0bbc1b54a49bad2815.py].
> Target weights are saved as [9b2b46ad93cb4c0bbc1b54a49bad2815.npy].
> WARNING: Logging before InitGoogleLogging() is written to STDERR
> I0601 14:13:37.378664 11640 net.cpp:51] Initializing net from parameters:
> state {
>   phase: TRAIN
>   level: 0
> }
> I0601 14:13:37.378664 11640 net.cpp:255] Network initialization done.
> W0601 14:13:37.379667 11640 _caffe.cpp:175] DEPRECATION WARNING - deprecated use of Python interface
> W0601 14:13:37.379667 11640 _caffe.cpp:176] Use this instead (with the named "weights" parameter):
> W0601 14:13:37.379667 11640 _caffe.cpp:178] Net('mobilenet_v1_caffe.prototxt', 1, weights='mobilenet_v1_caffe.caffemodel')
> I0601 14:13:37.380669 11640 net.cpp:51] Initializing net from parameters:
> state {
>   phase: TEST
>   level: 0
> }
> I0601 14:13:37.380669 11640 net.cpp:255] Network initialization done.
> Caffe model files are saved as [mobilenet_v1_caffe.prototxt] and [mobilenet_v1_caffe.caffemodel], 
> generated by [9b2b46ad93cb4c0bbc1b54a49bad2815.py] and [9b2b46ad93cb4c0bbc1b54a49bad2815.npy].

unfortunatly the resulting files
mobilenet_v1_caffe.caffemodel and mobilenet_v1_caffe.prototxt
are empty (or more detailed: they have 2 lines which are empty)

**Comment by namizzz** [comment]
Hi @svebert , MMdnn can only convert the architecture of a network, so the destination node can't be 'Squeeze', it contains the box predictor part which has not been supported now. We support to extract subgraph in tensorflow parser now. You can try te following script:
```cmd
python -m mmdnn.conversion._script.convert -sf tensorflow -in ./issue/model.ckpt.meta -iw ./issue/model.ckpt -df caffe --inputShape 224 224 3 --dstNodeName FeatureExtractor/MobilenetV1/Conv2d_13_pointwise_2_Conv2d_5_3x3_s2_128/Relu6 --inNodeName Preprocessor/sub  -om mobilenet_v1_caffe
```
and see if it works? Thanks.
