### ISSUE TITLE
mmdownload tensorflow for mobilenet_v1 does not work

### ISSUE THREAD

**Issue by svebert** [Microsoft/MMdnn#226]
Platform (like ubuntu 16.04/win10):
Win 10
Python version:
Python 3.5.4
Source framework with version (like Tensorflow 1.4.1 with GPU):
TF 1.8.0 with GPU
Destination framework with version (like CNTK 2.3 with GPU):
2.5.1
Pre-trained model path (webpath or webdisk path):
model.ckpt.meta: https://ufile.io/vssw2
model.ckpt.index: https://ufile.io/2q0ge
model.ckpt.data-00000-of-00001: https://ufile.io/97p1v
Running scripts:
> mmdownload -f tensorflow -n mobilenet_v1_1.0

> I get the following error message:
> Traceback (most recent call last):
>   File "c:\python3\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\python3\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Python3\Scripts\mmdownload.exe\__main__.py", line 9, in <module>
>   File "c:\python3\lib\site-packages\mmdnn\conversion\_script\extractModel.py", line 122, in _main
>     extract_model(args)
>   File "c:\python3\lib\site-packages\mmdnn\conversion\_script\extractModel.py", line 34, in extract_model
>     from mmdnn.conversion.examples.tensorflow.extractor import tensorflow_extractor
>   File "c:\python3\lib\site-packages\mmdnn\conversion\examples\tensorflow\extractor.py", line 18, in <module>
>     from mmdnn.conversion.examples.tensorflow.models.mobilenet import mobilenet_v2
> ImportError: No module named 'mmdnn.conversion.examples.tensorflow.models.mobilenet'

Has this something to do with a not configured proxy? How to configure a proxy?

Any help would be highly appreciated

**Comment by namizzz** [comment]
Hi @svebert ,Do you use the newest code? I try the python2/3 in ubuntu and python3 in windows.There is no error.

**Comment by bonne658** [comment]
I install an old version to solve this problem, but it looks like some layers aren't supported in old version.

**Comment by kitstar** [comment]
Hi @svebert and @bonne658 , could you try to update the mmdnn to master branch with
```bash
pip install -U git+https://github.com/Microsoft/MMdnn.git@master
```
and see if it works? Thanks.

**Comment by bonne658** [comment]
I have tried `pip install -U git+https://github.com/Microsoft/MMdnn.git@master` before  installing an old version, but I got an error.

**Comment by kitstar** [comment]
Hi @bonne658. Can't reproduce this error in my machine but found there is not __init__.py in mobilenet_v2 directory. Updated in newest check-in. Please help to check it again if it is convenient. 

Thank you for reporting the bug!

**Comment by svebert** [comment]
I installed mmdnn via pip on pyton3.5

I moved away from mmdnn, as my I found out that openCV 3.3 can load tensorflow models in C++ and it is easier for me to use openCV, than porting tensorflow model to caffe to use caffe in C++
