### ISSUE TITLE
Convert Yolov3 / RetinaNet from Keras to TensorFlow

### ISSUE THREAD

**Issue by why702** [Microsoft/MMdnn#236]
Sorry, I have no idea about how to convert the model from keras to tensorflow.

Yolov3: https://github.com/qqwweee/keras-yolo3 
RetinaNet: https://github.com/fizyr/keras-retinanet

Could you help me?

**Comment by JiahaoYao** [comment]
Hi @why702 , 
For the [`yolo3`](https://github.com/qqwweee/keras-yolo3), please follow the below process.

First, you shall use the latest MMdnn code. 
```bash 
pip install -U git+https://github.com/Microsoft/MMdnn.git@master
```
Secondly, git clone [`yolo3`](https://github.com/qqwweee/keras-yolo3). 
- `wget https://pjreddie.com/media/files/darknet53.conv.74`
- rename it as darknet53.weights
- modified `convert.py`
  - At [Line 88](https://github.com/qqwweee/keras-yolo3/blob/master/convert.py#L88), change `input_layer = Input(shape=(None, None, 3))` to  `input_layer = Input(shape=(416, 416, 3))`
  - At [Line 240](https://github.com/qqwweee/keras-yolo3/blob/master/convert.py#L240), add the code to generate `json` file.
```
    json_string = model.to_json()
    open('darknet53.json','w').write(json_string)
```
- `python convert.py -w darknet53.cfg darknet53.weights model_data/darknet53_weights.h5`

Thirdly, Convert the `keras` to `IR`
```bash
mmtoir -f keras -d yolo3 -n /Users/kit/Downloads/darknet53.json -w /Users/kit/Downloads/darknet53_weights.h5
```

You will get 
```
IR network structure is saved as [yolo3.json].
IR network structure is saved as [yolo3.pb].
IR weights are saved as [yolo3.npy].
```
Finally, Convert models from IR to Tensorflow code snippet.

```bash
mmtocode -f tensorflow --IRModelPath yolo3.pb --IRWeightPath yolo3.npy --dstModelPath tf_yolo3.py
```
You will get the Tensorflow code snippet then.
```
Parse file [yolo3.pb] with binary format successfully.
Target network code snippet is saved as [tf_yolo3.py].
```

**Comment by JiahaoYao** [comment]
For [`retinanet`](https://github.com/fizyr/keras-retinanet), it might not be supported currently in `MMdnn`. For the sake of generality, the most general layers are supported in MMdnn.

In  retinanet, there are general layers like this. They can be converted correctly.
![image](https://user-images.githubusercontent.com/20907377/41148632-068aa074-6b3c-11e8-99dd-ea1102bd35b9.png)

However, in the very end of retinanet, there are layer like this.
![image](https://user-images.githubusercontent.com/20907377/41148679-2a0c4200-6b3c-11e8-8675-690cfaef2176.png)

If you can provide the pretrained model without these layers, the comnversion could be possibly carried on.

**Comment by why702** [comment]
Hi JiahaoYao

I follow your process step by step, and get success. It's amazing. Thanks a lot.

But when I use the yolov3 weight like: wget https://pjreddie.com/media/files/yolov3.weights
get the following error message:

> Network file [yolov3.json] and [model_data/yolov3.h5] is loaded successfully.
> KerasParser has not supported operator [UpSampling2D].
> {'name': 'up_sampling2d_1', 'trainable': True, 'size': (2, 2), 'data_format': 'channels_last'}
> KerasParser has not supported operator [UpSampling2D].
> {'name': 'up_sampling2d_2', 'trainable': True, 'size': (2, 2), 'data_format': 'channels_last'}
> IR network structure is saved as [yolo3.json].
> IR network structure is saved as [yolo3.pb].
> IR weights are saved as [yolo3.npy].

I used MMdnn model visualizer to check the yolo3.json. It's still have the UpSampling2D node.
Is this mean the yolo3.pb or yolo3.npy are not completed?
Do you have any suggestion?
Thx

**Comment by JiahaoYao** [comment]
Thank you @why702 for your feedback. I am creating a pull request to add the `upsampling2d` for `mmdnn`.  Hoping it can solve your problem.

**Comment by why702** [comment]
Hi @JiahaoYao 
When I upgrade the MMdnn
pip install -U git+https://github.com/Microsoft/MMdnn.git@master
and follow your process but the error message when I do the cmd:

> mmtoir -f keras -d yolo3 -n ./model_data/yolov3.json -w ./model_data/yolov3.h5

> Traceback (most recent call last):
>   File "/home/bill/anaconda3/bin/mmtoir", line 11, in <module>
>     sys.exit(_main())
>   File "/home/bill/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 184, in _main
>     ret = _convert(args)
>   File "/home/bill/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 7, in _convert
>     inputshape = [int(x) for x in args.inputShape]
> TypeError: 'NoneType' object is not iterable

And I check my JSON "./model_data/yolov3.json" input shape:
"batch_input_shape": [null, 416, 416, 3]

Do you know what happen?

**Comment by JiahaoYao** [comment]
Hi @why702 , the error reported is not because of your model, but actually due to `mmdnn/conversion/_script/convertToIR.py`. Hoping this pull request could help you.

**Comment by why702** [comment]
Hi @JiahaoYao 
I think it's success.
Thanks a lot. I very appreciate your help.

**Comment by bundelesneha05** [comment]
> Hi @why702 ,
> For the [`yolo3`](https://github.com/qqwweee/keras-yolo3), please follow the below process.
> 
> First, you shall use the latest MMdnn code.
> 
> ```shell
> pip install -U git+https://github.com/Microsoft/MMdnn.git@master
> ```
> 
> Secondly, git clone [`yolo3`](https://github.com/qqwweee/keras-yolo3).
> 
> * `wget https://pjreddie.com/media/files/darknet53.conv.74`
> * rename it as darknet53.weights
> * modified `convert.py`
>   
>   * At [Line 88](https://github.com/qqwweee/keras-yolo3/blob/master/convert.py#L88), change `input_layer = Input(shape=(None, None, 3))` to  `input_layer = Input(shape=(416, 416, 3))`
>   * At [Line 240](https://github.com/qqwweee/keras-yolo3/blob/master/convert.py#L240), add the code to generate `json` file.
> 
> ```
>     json_string = model.to_json()
>     open('darknet53.json','w').write(json_string)
> ```
> * `python convert.py -w darknet53.cfg darknet53.weights model_data/darknet53_weights.h5`
> 
> Thirdly, Convert the `keras` to `IR`
> 
> ```shell
> mmtoir -f keras -d yolo3 -n /Users/kit/Downloads/darknet53.json -w /Users/kit/Downloads/darknet53_weights.h5
> ```
> 
> You will get
> 
> ```
> IR network structure is saved as [yolo3.json].
> IR network structure is saved as [yolo3.pb].
> IR weights are saved as [yolo3.npy].
> ```
> Finally, Convert models from IR to Tensorflow code snippet.
> 
> ```shell
> mmtocode -f tensorflow --IRModelPath yolo3.pb --IRWeightPath yolo3.npy --dstModelPath tf_yolo3.py
> ```
> 
> You will get the Tensorflow code snippet then.
> 
> ```
> Parse file [yolo3.pb] with binary format successfully.
> Target network code snippet is saved as [tf_yolo3.py].
> ```
where it this file tf_yolo.py?

**Comment by LuckyHouse** [comment]
> Hi @why702 ,
> For the [`yolo3`](https://github.com/qqwweee/keras-yolo3), please follow the below process.
> 
> First, you shall use the latest MMdnn code.
> 
> ```shell
> pip install -U git+https://github.com/Microsoft/MMdnn.git@master
> ```
> 
> Secondly, git clone [`yolo3`](https://github.com/qqwweee/keras-yolo3).
> 
>     * `wget https://pjreddie.com/media/files/darknet53.conv.74`
> 
>     * rename it as darknet53.weights
> 
>     * modified `convert.py`
>       
>       * At [Line 88](https://github.com/qqwweee/keras-yolo3/blob/master/convert.py#L88), change `input_layer = Input(shape=(None, None, 3))` to  `input_layer = Input(shape=(416, 416, 3))`
>       * At [Line 240](https://github.com/qqwweee/keras-yolo3/blob/master/convert.py#L240), add the code to generate `json` file.
> 
> 
> ```
>     json_string = model.to_json()
>     open('darknet53.json','w').write(json_string)
> ```
> 
>     * `python convert.py -w darknet53.cfg darknet53.weights model_data/darknet53_weights.h5`
> 
> 
> Thirdly, Convert the `keras` to `IR`
> 
> ```shell
> mmtoir -f keras -d yolo3 -n /Users/kit/Downloads/darknet53.json -w /Users/kit/Downloads/darknet53_weights.h5
> ```
> 
> You will get
> 
> ```
> IR network structure is saved as [yolo3.json].
> IR network structure is saved as [yolo3.pb].
> IR weights are saved as [yolo3.npy].
> ```
> 
> Finally, Convert models from IR to Tensorflow code snippet.
> 
> ```shell
> mmtocode -f tensorflow --IRModelPath yolo3.pb --IRWeightPath yolo3.npy --dstModelPath tf_yolo3.py
> ```
> 
> You will get the Tensorflow code snippet then.
> 
> ```
> Parse file [yolo3.pb] with binary format successfully.
> Target network code snippet is saved as [tf_yolo3.py].
> ```

After the cmd 'mmtoir -f keras -d yolo3 -n darknet53.json -w model_data/darknet53_weights.h5':

> Traceback (most recent call last):
>   File "/home/xu/miniconda3/envs/p3/bin/mmtoir", line 8, in <module>
>     sys.exit(_main())
>   File "/home/xu/miniconda3/envs/p3/lib/python3.8/site-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
>     ret = _convert(args)
>   File "/home/xu/miniconda3/envs/p3/lib/python3.8/site-packages/mmdnn/conversion/_script/convertToIR.py", line 46, in _convert
>     parser = Keras2Parser(model)
>   File "/home/xu/miniconda3/envs/p3/lib/python3.8/site-packages/mmdnn/conversion/keras/keras2_parser.py", line 136, in __init__
>     self.keras_graph.build()
>   File "/home/xu/miniconda3/envs/p3/lib/python3.8/site-packages/mmdnn/conversion/keras/keras2_graph.py", line 48, in build
>     for pred in node.inbound_layers:
> TypeError: 'InputLayer' object is not iterable

Is this my version problem？
