### ISSUE TITLE
ONNX support

### ISSUE THREAD

**Issue by pliniosilveira** [Microsoft/MMdnn#25]
Hi, guys.

How does MMdnn relates to ONNX?

Do you guys use it as IR or have plans for that?

Thank you

**Comment by kitstar** [comment]
Hi @pliniosilveira,
ONNX support is in our plan. For IR, our ops are similar but still have some difference.

**Comment by pliniosilveira** [comment]
That means the current IR will be abandoned sooner or later or somehow they may coexist?
Or maybe you didn't stop to think about it yet?

**Comment by kitstar** [comment]
In our plan, onnx will be treated as other framework, with the parser and emitter. And we may refer the ONNX ops' defination to refine ours.

**Comment by BenPYeh** [comment]
Will there be an update with this soon?

**Comment by namizzz** [comment]
Hi @BenPYeh, we have implement the onnx support now.Try the newest code. Thanks!
