### ISSUE TITLE
After TensorFlow->Caffe conversion, output after flatten layer permuted in a different way

### ISSUE THREAD

**Issue by shubh-agrawal** [Microsoft/MMdnn#250]
Platform (like ubuntu 16.04/win10): ubuntu 16.04
Python version: Python 2.7
Source framework with version (like Tensorflow 1.4.1 with GPU): Tensorflow 1.8.0
Destination framework with version (like CNTK 2.3 with GPU): Caffe
Pre-trained model path (webpath or webdisk path): https://drive.google.com/file/d/1yPmI8EJERpaS0o5m3SRIIg9r8kyJuVui/view?usp=sharing

The trained model is of type: conv->relu->conv.......->pool->flatten->fc->fc->fc

After converting my frozen graph entropy.pb to caffe converted entropy.prototxt and entropy.caffemodel, I was able to run the network in caffe API. However, after giving same input to tensorflow and caffe separately, I received different output. So I debugged this layer by layer and found out that the flatten layer after each model gives the same output, but with different permutation. This is understood as tensorflow used `nhwc` format while the caffe uses `nchw` format. I expected that the conversion would automatically add a permutation layer before flatten layer so that the coming fully connected layers are multiplied appropriately. Was this problem expected or has been taken care of using a work-around? 
A good implementation is made in opencv, wherein they automatically add a permutation layer when parsing a tensorflow model.

I used this command for conversion,
```
mmconvert -sf tensorflow --frozen_pb entropy.pb -df caffe --inputShape 108 140 1 --dstNodeName Dense2/fc5/BiasAdd --inNodeName X -om entropy_caffe
```

Thanks for helping.

**Comment by namizzz** [comment]
Hi @shubh-agrawal , Thanks for your issue. We have fixed the bug you mentioned. Try the newest code!

**Comment by shubh-agrawal** [comment]
That's really great! It works like a charm now. Thanks @namizzz and @kitstar.
