### ISSUE TITLE
caffe conversion

### ISSUE THREAD

**Issue by SANTO-P** [Microsoft/MMdnn#252]
What is the command to convert caffe model to tensorflow? and can caffe model be converted to keras?

**Comment by JiahaoYao** [comment]
Hi @SANTO-P , here is something that might give you some inspiration and suggestion when using `MMdnn`. You can check it out at [Samples of conversion between different frameworks].(https://github.com/Microsoft/MMdnn#support-frameworks)

**Comment by SANTO-P** [comment]
$ mmconvert -sf caffe -in resnet152-deploy.prototxt -iw resnet152.caffemodel -df cntk -om caffe_resnet152.dnn

As this command converts caffe to cntk....what parameters to be included in command for caffe to keras conversion?

**Comment by JiahaoYao** [comment]
Here is my suggestion. 
First, convert the caffe model to IR structure by following [`caffe->IR`](https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/caffe/README.md#convert-models-from-caffe-to-ir-caffe---ir).
```bash
$ mmtoir -f caffe -n resnet152-deploy.prototxt -w resnet152.caffemodel -o caffe_resnet_IR
.
.
.
IR network structure is saved as [caffe_resnet_IR.json].
IR network structure is saved as [caffe_resnet_IR.pb].
IR weights are saved as [caffe_resnet_IR.npy].
```

Then, convert the IR structure to the keras code by following [`IR->Keras`](https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/keras/README.md#convert-models-from-ir-to-keras-code-snippet).

```bash
$ mmtocode -f keras --IRModelPath caffe_resnet_IR.pb --dstModelPath keras_inception_v3.py

Parse file [caffe_resnet_IR.pb] with binary format successfully.
Target network code snippet is saved as [keras_inception_v3.py].
```
Hoping this could be helpful to you.
