### ISSUE TITLE
Question: Pytorch Convert to IR

### ISSUE THREAD

**Issue by SmallMunich** [Microsoft/MMdnn#266]
Platform (like ubuntu 16.04):
Python version : 2.7
Source framework with version (pytorch 0.4.0 with GPU):
Destination framework with version (like TensorFlow with GPU):

Using MMdnn to transform model( Pytorch -> IR ), the report is that No module named 'xxx' or ImportError: No module named 'xxx' .  This 'xxx' is network file(.py file).Do I want to know if MMdnn can convert its own network-trained models?(ps: the network is self-designed)

**Comment by JiahaoYao** [comment]
Hi @SmallMunich , Could you be a little bit more specific? You can show me the script you use in the bash and paste the error here. Your file is also appreciated.

**Comment by SmallMunich** [comment]
ok, @JiahaoYao !

The error is : 
wupeng@ubuntu:~/workshop$ mmtoir -f pytorch -d cpm_fpn --inputShape 3 368 368 -n _0621_100.pth               
/home/wupeng/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):

  File "/home/wupeng/anaconda3/bin/mmtoir", line 11, in <module>
    sys.exit(_main())
  File "/home/wupeng/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/_scrip/convertToIR.py", line 184, in _main
              ret = _convert(args)
  File "/home/wupeng/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/_scrip/convertToIR.py", line 79, in _convert
              parser = PytorchParser(args.network, inputshape)
  File "/home/wupeng/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/pytorc/pytorch_parser.py", line 71, in __init__
             model = torch.load(model_file_name)
  File "/home/wupeng/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 303, in load
            return _load(f, map_location, pickle_module)
  File "/home/wupeng/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 469, in _load
           result = unpickler.load()

**ModuleNotFoundError: No module named 'CPM_FPN3_cpmadd6_dress'**

The 'CPM_FPN3_cpmadd6_dress' is the network file(.py). 

Its training model using inference partly(reading the model and predicting…… ps: the pytorch model saved the whole in training process) : 

def main():
    os.environ['CUDA_VISIBLE_DEVICES'] = '0,1,2,3'
    import models.CPM_FPN3_cpmadd6_dress
    pytorch_model = './_0621_100.pth'  
    model = models.CPM_FPN3_cpmadd6_dress.pose_estimation(class_num=15, pretrain=False)
    .......

when I using the command line: pytorch ->IR. the input parameters has not CPM_FPN3_cpmadd6_dress. Because the CPM_FPN3_cpmadd6_dress.py is the network file self-designing. 

the CPM_FPN3_cpmadd6_dress.py link as follows:
      https://github.com/SmallMunich/question/blob/master/CPM_FPN3_cpmadd6_dress.py 

    Do I want to know if the network structure designed by myself is supported in the Pytorch-conversion IR process?

**Comment by JiahaoYao** [comment]
Hi @SmallMunich ,
First, the self-designed network is supported by `MMdnn`. Like the `pytest` in MMdnn, they use the model from torchvision( [detail](https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/examples/pytorch/extract_model.py#L15-L20) ). 
For example,
```
import torchvision.models as models
model = models.vgg16(pretrained=True)
```

I do not know why you can not load the model, and do you use the [`torch.save(model)`](https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/examples/pytorch/extract_model.py#L39) to save the whole model, not just save the `state_dict`?

**Comment by HongChow** [comment]
@SmallMunich Hi,  can you fix the problem now? I met the same problem as you. And I'm confused...
