### ISSUE TITLE
[bug]: is it a typo in pytorch_parser.py

### ISSUE THREAD

**Issue by qigtang** [Microsoft/MMdnn#272]
![image](https://user-images.githubusercontent.com/7813095/41954683-85ae2ee4-7991-11e8-95b2-27589918c5a6.png)

file mmdnn/conversion/pytorch/pytorch_parser.py, line number 459, it should be

kwargs['pooling_type'] = 'AVG'

instead of 

kwargs['pooling_type'] = 'MAX'

right?

**Comment by JiahaoYao** [comment]
Hi @qigtang , 
Cool! You are right! Thank you for supporting `MMdnn`!
