### ISSUE TITLE
Run the demo occured problem...

### ISSUE THREAD

**Issue by zhiweichen12** [Microsoft/MMdnn#274]
Platform (like ubuntu 16.04/win10):ubuntu

Python version:2.7.6 

convert pytorch to IR 

Running scripts:

$ mmtoir -f pytorch -d resnet50 --inputShape 3 224 224 -n imagenet_resnet50.pth

ImportError: cannot import name _unique_state_dict

thanks!

**Comment by JiahaoYao** [comment]
Hi @zhiweichen12 ,
Please tell me what version of your pytorch. Is it the latest?

**Comment by asaydin** [comment]
Hi @JiahaoYao, 

I am experiencing the same problem. My PyTorch version is 0.3.0.post4 with Python 3.6.5.

**Comment by JiahaoYao** [comment]
I think upgrading pytorch to the latest version can solve the problem.

-------
I find the resnet50 have the following problem. The same problem is also mentioned [here](https://discuss.pytorch.org/t/batchnorm2d-object-has-no-attribute-track-running-stats/17525), but we can not downgrade the pytorch back to 0.3.1. That way might result in `_unique_state_dict` import error. 
![image](https://user-images.githubusercontent.com/20907377/42079067-471dd982-7bb1-11e8-87f3-95a02d059a5f.png)

If you change from `resnet50` to `resnet101`, the above problem does not appear. you will get the result like this. 
![image](https://user-images.githubusercontent.com/20907377/42079305-e598c6e4-7bb1-11e8-9bb8-9f9467931a2e.png)
