### ISSUE TITLE
CaffeEmitter has not supported operator [ResizeBilinear].

### ISSUE THREAD

**Issue by ujsyehao** [Microsoft/MMdnn#277]
When I turn a tensorflow pose model into caffe model, it prompts the error "**CaffeEmitter has not supported operator [ResizeBilinear].**", my tensorflow pose model has this operator, So how can I solve it?
I have **two thoughts**:

- Firstly add the ResizeBilinear layer in cafffe, then I use mmdnn, **Do mmdnn support newly add layers in caffe?**  **What does mmdnn work?**

- Another thought is **to convert tensorflow model to caffe model directly** because ResizeBilinear layer **doesn't have weights**, so I can remove correlation ResizeBilinear layer in my model structure, **then I add these layers in caffe model prototxt manually(Assuming I have implemented ResizeBilinear layer in caffe).**

**Comment by kitstar** [comment]
Hi @ujsyehao, we can set the input node of tensorflow parser to skip this node. @namizzz can help with the argument of TF parser.

**Comment by ujsyehao** [comment]
Thank you @kitstar, I have implemented ResizeBilinear layer in caffe(own) and am testing the newly added layer.
I am looking forward to @namizzz instructions, Can you give me some details about mmdnn's conversion to caffe?

**Comment by namizzz** [comment]
Hi @ujsyehao ,Here is the [README](https://github.com/Microsoft/MMdnn/tree/master/mmdnn/conversion/tensorflow#tensorflow-readme)

**Comment by ujsyehao** [comment]
@namizzz Hi, the README doesn't include skip nodes, Can you tell me how to set the input node of tensorflow parser to skip this node?

**Comment by namizzz** [comment]
@ujsyehao  Please read the whole command in this [part ](https://github.com/Microsoft/MMdnn/tree/master/mmdnn/conversion/tensorflow#one-step-conversion)

 **--inputShape 224,224,3 --dstNodeName FeatureExtractor/MobilenetV1/Conv2d_13_pointwise_2_Conv2d_5_3x3_s2_128/Relu6 --inNodeName Preprocessor/sub**

**Comment by namizzz** [comment]
Hi, @ujsyehao 
If you can skip this node, you can get IR from Tensorflow and then convert it to caffe model code file.Now you only need to add this layer into the caffe model.

**Comment by ujsyehao** [comment]
@namizzz Hi, when I turn IR to caffe model, it shows the error:

> CaffeEmitter has not supported operator [ResizeBilinear].

So I add emit_ResizeBilinear function in caffe_emitter.py, 
![166](https://user-images.githubusercontent.com/17454232/42258680-7ed038e8-7f8f-11e8-9ca6-de9fd382ac2a.png)
However, I do not know IR_node.get_attr()(what's the IR properties of ResizeBilinear op).

**Comment by namizzz** [comment]
Hi @ujsyehao  
As you say ,you need to skip this node in Tensorflow parser first ,then get IR file to convert it to Caffe model file, so you will not meet this problem in CaffeEmit. Thanks!

**Comment by ujsyehao** [comment]
@namizzz I don't need to skip this node in Tensorflow, I can directly modify conversion/caffe/caffe_emitter.py to make it support ResizeBilinear operator, code shown below:
![169](https://user-images.githubusercontent.com/17454232/42357782-233e129c-810c-11e8-969a-e60485ae2447.png)
then modify conversio/caffe/graph.py add this:
![170](https://user-images.githubusercontent.com/17454232/42357815-4f2e9ffc-810c-11e8-8e46-ecd70e040aa7.png)

**Comment by namizzz** [comment]
Hi @ujsyehao ,OK! It's pretty good you can add this part by yourself. Fisrt you need to get the attribute from the source_node, and then add the necessary IR properties in "rename_ResizeBilinear" op in the TF parser. If you use TF model file (.pb), you need to modify the "tensorflow_frozenparser". If you use .ckpt ,you need to modify the "tensorflow_parser". 
Here is the [Contribution-Guideline](https://github.com/Microsoft/MMdnn/wiki/Contribution-Guideline).Thanks and sorry!

**Comment by ujsyehao** [comment]
For ResizeBilinear operation, I only implement IR -> caffe now, so I need to implement caffe -> IR(get the attribute from the source_node), IR -> tensorflow(add IR properties in TF parser and modify tensorflow_*parser). 
Thanks for your kind! I will do later.

**Comment by namizzz** [comment]
Hi @ujsyehao , yes!
But there is something wrong I think if you need to turn a tensorflow pose model into caffe model.
1. implement TF to IR (get the attribute from the source_node and also add IR properties to IR node) in the TF parser file.
2.IR to Caffe (get IR properties above).

Thanks!
