### ISSUE TITLE
Getting this issue while trying to install MMdnn

### ISSUE THREAD

**Issue by anshumankmr97** [Microsoft/MMdnn#289]
`jupyterlab 0.32.1 has requirement jupyterlab_launcher<0.11.0,>=0.10.0, but you'll have jupyterlab-launcher 0.11.0 which is incompatible.
`
Here is some other information, if required
Platform (ubuntu 16.04):

Python version: 3.6 

Source framework with version (like Tensorflow 1.4.1 with GPU):

Destination framework with version (like MxNet with GPU):

**Comment by namizzz** [comment]
Hi @anshumankmr97 , MMdnn doesn't have requirement about jupyter.
