### ISSUE TITLE
ImportError: Import by filename is not supported

### ISSUE THREAD

**Issue by xmfbit** [Microsoft/MMdnn#298]
I tried to use MMDNN to convert  a model trained by MXNet to PyTorch. These are my system info:
```
Platform: Debian 8.9

Python version: Python 2.7

Source framework with version: MXNet 1.2.0 with GPU

Destination framework with version: PyTorch 1.4.0 with GPU
```

Running scripts: 
```
mmconvert --srcFramework mxnet --dstFramework pytorch --inputWeight ~/model-0000.params --inputNetwork ~/model-symbol.json --outputModel ./mmdnn_output/output --inputShape 3 224 224
```

The error message is:
```
  File "/home/me/anaconda2/lib/python2.7/site-packages/mmdnn/conversion/_script/dump_code.py", line 11, in dump_code
    MainModel = __import__(network_filepath)
ImportError: Import by filename is not supported.
```

Inspired by this question in SO [How to import a module given the full path?](https://stackoverflow.com/questions/67631/how-to-import-a-module-given-the-full-path), I modified Line 11 of `dump_code.py` like this:
```
import imp
# Line 11
MainModel = imp.load_source('MainModel', network_filepath + '.py')
```
It works. 

I did other experiments to convert the model. If the output directory is given, the error occurs. The problem seems that we cannot import python file with full path using `__import__(file_path)` if the file is not in the current directory.

**Comment by kitstar** [comment]
Hi @xmfbit , thanks for helping diagnose this problem!

**Comment by namizzz** [comment]
Hi @xmfbit , do you use the newest version MMdnn? I test the conversion, there seems no problem.Or can you provide your model file?

**Comment by kitstar** [comment]
Hi @xmfbit fixed in recent commit. Thanks again for reporting this issue.
