### ISSUE TITLE
Convert Special ResNet101 from TensorFlow to PyTorch

### ISSUE THREAD

**Issue by ahkarami** [Microsoft/MMdnn#31]
Dear @kitstar,
By using your complete [tutorial](https://github.com/Microsoft/MMdnn/issues/22) I can convert _ResNet V1 101_ model (from TF-Slim) to PyTorch, and the converted model works correct. Now I want to convert another _ResNet V1 101_ model which has 5,000 classes from TensorFlow to PyTorch. In fact, I want to convert the pre-trained [_Open Images ResNet V1 101_](https://github.com/openimages/dataset) from TensorFlow to PyTorch. 
To this end, I have tested with follow steps:

1. Download resnet_v1_101 data:
```
$ wget https://storage.googleapis.com/openimages/2017_07/oidv2-resnet_v1_101.ckpt.tar.gz
$ tar -xvf oidv2-resnet_v1_101.ckpt.tar.gz

```
2. Extract tf model files:
`python -m mmdnn.conversion.examples.tensorflow.extract_model -n resnet_v1_101 -ckpt oidv2-resnet_v1_101.ckpt.data-00000-of-00001`

However, I got a long error like this:
```
... DataLossError (see above for traceback): Unable to open table file ./oidv2-resnet_v1_101.ckpt.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
```
I used the TF 1.4.1 and PyTorch 0.3.
Would you please help me to address this issue and do the conversion?

**Comment by kitstar** [comment]
Hi, the extract_model.py of tf is an **example code** to show how to generate the full checkpoint files. You should modify **your own inference code** to generate your own checkpoint files.
