### ISSUE TITLE
support asymmetric padding without implementing custom layers in caffe when converting tf to caffe

### ISSUE THREAD

**Issue by CuiXiaoDao** [Microsoft/MMdnn#314]
The padding problem is well explained in [Error in mobilenet conversion from Tensorflow to Caffe Different way of padding](https://github.com/Microsoft/MMdnn/wiki/Error-in-mobilenet-conversion-from-Tensorflow-to-Caffe-Different-way-of-padding).

A possible solution is implementing a custom padding layer in caffe and then modifying mmdnn to use that layer, which needs a lot of extra work. I think we could use symmetric padding and then crop when converting, which is easier for users.
For example, when converting a convolution layer 'conv_2D_6' of of padding like` (pad_w, pad_h, pad_w+1, pad_h)` from tensorflow to caffe (note for tensorflow, asymmetric padding can only be `pad_w` vs `pad_w+1`, `pad_`h vs `pad_h+1`, if I haven't got wrong): 
1. change the horizontal padding from `(pad_w,pad_w+1)` to `(pad_w+stride, pad_w+1+(stride-1))`. 
The extra paddings of length stride at left brings one extra column at left of the convolution result while extra paddings of length (stride-1) at right is discarded during convolution. So the result of inputs with symmetric padding is the original result plus one extra column at left.
2. use a crop layer remove the first column.

The same strategy applies to pool layer.

After using that, our model passed the test with error=1e-5, L1 error=0.006, SNR=64.10, PSNR=79.12.
I also tested on MobileNets v1, it achieves a better result than the wiki. 

>Result after modifying:
> error: 0.29709578305482864
> L1 error: 0.6029861
> SNR: 6.288722375836028
> PSNR: 36.219608961427426
> Origin result on wiki:
> error: 0.61917245
> L1 error: 1431.8882
> SNR: 5.100172946375377
> PSNR: 19.59308572747237

By computing the SNR of input and output of each layer, I think the reason for the still poor SNR of MobileNets v1, seems to be relu6, which is not supported in caffe.

**Comment by ujsyehao** [comment]
you can look it #153

**Comment by CuiXiaoDao** [comment]
@ujsyehao Thanks, I hadn't found a similar approach has been implemented.

**Comment by ujsyehao** [comment]
@CuiXiaoDao It is an effective method, the relu6 layer is easy to implement.
