### ISSUE TITLE
The json file is empty from tensorflow to IR

### ISSUE THREAD

**Issue by JackieLeeTHU11** [Microsoft/MMdnn#32]
I try to convert tensorflow to IR, with the following commond:

`python -m mmdnn.conversion._script.convertToIR -f tensorflow -d selfDesignNetwork -n selfDesignNetwork.ckpt.meta --dstNodeName output/weights`

However the result json file and .pb file is empty .

selfDesignNetwork.ckpt.meta is the .meta file and output/weights is the output node name.

What's wrong with the problem?

**Comment by kitstar** [comment]
Hi, could you share the model files and output logs?

**Comment by JackieLeeTHU11** [comment]
@kitstar 
The commond is
`python -m mmdnn.conversion._script.convertToIR -f tensorflow -d smallnet_v3 -n smallnet_v3_CSattention/smallnet_v3.ckpt.meta --dstNodeName 3dface_smallnet_v3/e_Regresion/e_regresion_layer/weights`

the output log is:
`Parse file [smallnet_v3_CSattention/smallnet_v3.ckpt.meta] with binary format successfully.
Tensorflow model file [smallnet_v3_CSattention/smallnet_v3.ckpt.meta] loaded successfully.
IR network structure is saved as [smallnet_v3.json].
IR network structure is saved as [smallnet_v3.pb].
Warning: weights are not loaded.`

**Comment by kitstar** [comment]
Hi, your dstNode is squeeze_logits, please try it again. And there are some layers conversion not completed. I will inform you if it finishs.
Thanks.

**Comment by JackieLeeTHU11** [comment]
@kitstar Hi, you are right. However, when I set dstNode with squeeze_logits, there is a bug. And the log is:
`File "mmdnn/conversion/tensorflow/tensorflow_parser.py", line 281, in gen_IR
    func(current_node)

  File "mmdnn/conversion/tensorflow/tensorflow_parser.py", line 360, in rename_Conv2D
    IR_node = self._convert_identity_operation(source_node, 1, 'Conv')

  File "mmdnn/conversion/tensorflow/tensorflow_parser.py", line 387, in _convert_identity_operation
    TensorflowParser._copy_and_reop(source_node, IR_node, new_op)

  File "mmdnn/conversion/tensorflow/tensorflow_parser.py", line 303, in _copy_and_reop
    assign_IRnode_values(IR_node, kwargs)

  File "mmdnn/conversion/common/utils.py", line 45, in assign_IRnode_values
    assign_attr_value(IR_node.attr[name], val)

  File "mmdnn/conversion/common/utils.py", line 40, in assign_attr_value
    raise NotImplementedError('AttrValue cannot be of %s' % type(val))

NotImplementedError: AttrValue cannot be of <type 'unicode'>`

**Comment by kitstar** [comment]
It is a  compatibility problem between py2 and py3. Fixed in newest code.

**Comment by JackieLeeTHU11** [comment]
Ok, I will try the newest code. Thanks for your work!
