### ISSUE TITLE
AttributeError: 'NoneType'  error when transform Mxnet to Tensorflow

### ISSUE THREAD

**Issue by xmuszq** [Microsoft/MMdnn#322]
Platform (like ubuntu 16.04/win10):
ubuntu1604
Python version:
2.7
Source framework with version:
Mxnet GPU 1.2.0
Destination framework with version:
Tensorflow GPU
Pre-trained model path (webpath or webdisk path):
[pathlink](https://drive.google.com/drive/folders/1e9a6EN3edCXmR2eO9ZTxSfWTkhc8e9cE)
Running scripts:

I open this issue as I think this is a bug caused by the mmdnn package. 
I ran following commands:

`python -m mmdnn.conversion._script.convertToIR -f mxnet -n $path_json -w $path_paras -d $name_IR_output --inputShape 3,112,112
python -m mmdnn.conversion.script.IRToCode -f tensorflow --IRModelPath IR_output.pb --IRWeightPath IR_output.npy --dstModelPath tf_model.py`

I got error:

`transform the mxnet model to IR model using mmdnn.................... /home/zhen/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype fromfloattonp.floatingis deprecated. In future, it will be treated asnp.float64 == np.dtype(float).type. from ._conv import register_converters as _register_converters /usr/local/lib/python2.7/dist-packages/mxnet/module/base_module.py:54: UserWarning: You created Module with Module(..., label_names=['softmax_label']) but input with name 'softmax_label' is not found in symbol.list_arguments(). Did you mean one of: data warnings.warn(msg) Warning: MXNet Parser has not supported operator null with name data. Warning: convert the null operator with name [data] into input layer. Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 197, in <module> _main() File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main ret = _convert(args) File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 115, in _convert parser.run(args.dstPath) File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/common/DataStructure/parser.py", line 22, in run self.gen_IR() File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 262, in gen_IR func(current_node) File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 565, in rename_Pooling kernel_shape = MXNetParser.str2intList(source_node.get_attr("kernel")) File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 55, in str2intList v = v.replace("(", "") AttributeError: 'NoneType' object has no attribute 'replace'`

**Comment by namizzz** [comment]
Hi @xmuszq , there is a problem when mxnet_parser load_checkpoint (line 175). 
```code
mxnet.base.MXNetError: Required parameter kernel of Shape(tuple) is not presented, in operator Pooling(name="ave pooling", pool_type="avg", global_pool="True")
```
Is your mxnet version 1.0.0 ?

**Comment by xmuszq** [comment]
@namizzz 
Thank you for helping! 
I check with mx.__version__, and it shows the version is 1.2.0

**Comment by xmuszq** [comment]
@namizzz  
let me know if need me to do any testing.

**Comment by namizzz** [comment]
Hi @xmuszq , mmdnn don't support the MXNet >1.0.0 now. Maybe you can downgrade it, and save a model to use mmdnn. Thanks!
