### ISSUE TITLE
convert pytorch to caffe

### ISSUE THREAD

**Issue by knsong** [Microsoft/MMdnn#329]
Platform (like ubuntu 16.04/win10):
macos
Python version:
python2.7
Source framework with version (like Tensorflow 1.4.1 with GPU):
pytorch with cpu
Destination framework with version (like CNTK 2.3 with GPU):
pytorch with cpu

Is there any tutorial of  converting pytorch model to caffe model?

**Comment by namizzz** [comment]
Hi @knsong ,here are the [Pytorch README](https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/pytorch/README.md) and [Caffe README](https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/caffe/README.md).

**Comment by knsong** [comment]
Thanks, in fact [this](https://github.com/Microsoft/MMdnn/issues/241) saves my day. It's more detailed!
