### ISSUE TITLE
For TF convert to Caffe, Error occurs when running the frozen graph conversion example 

### ISSUE THREAD

**Issue by Zhengtq** [microsoft/MMdnn#330]
When running the example command "mmconvert -sf tensorflow -iw mobilenet_v1_1.0_224/frozen_graph.pb --inNodeName input --inputShape 224,224,3 --dstNodeName MobilenetV1/Predictions/Softmax -df caffe -om tf_mobilenet" , I got this error

" File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/tensorflow/tensorflow_frozenparser.py", line 255, in _convert_layers_batchnorm
beta = self.get_parent(output_node.name, [1, 0, 0], True).get_attr('value')
AttributeError: 'NoneType' object has no attribute 'get_attr'"

Can anyone tells me how to solve it?

**Comment by namizzz** [comment]
Hi @Zhengtq ,Which version tensorflow you are using ? MMdnn supports Tensorflow>1.8

**Comment by Zhengtq** [comment]
I am using Tensorflow 1.9

**Comment by namizzz** [comment]
Hi @Zhengtq , can you try Tensorflow 1.8 ? I think it can solve the problem.

**Comment by Zhengtq** [comment]
Ok, I will try it
