### ISSUE TITLE
run conversion tensorflow demo throw error

### ISSUE THREAD

**Issue by iChiaGuo** [Microsoft/MMdnn#333]
Platform (like ubuntu 16.04/win10):ubuntu 16.04

Python version:2.7

Source framework with version (like Tensorflow 1.4.1 with GPU):Tensorflow 1.8

Destination framework with version (like CNTK 2.3 with GPU):

Pre-trained model path (webpath or webdisk path): 
mmdownload -f tensorflow -n mobilenet_v1_1.0_frozen

Running scripts:
mmconvert -sf tensorflow -iw mobilenet_v1_1.0_224/frozen_graph.pb --inNodeName input --inputShape 224,224,3 --dstNodeName MobilenetV1/Predictions/Softmax -df caffe -om tf_mobilenet

IOError: [Errno 2] No such file or directory: u'10fbcb8263b040478e38db9b12032c16.npy'

**Comment by namizzz** [comment]
Hi @iChiaGuo ,it's because one of the IR files is missing. Do you delete it when converting?
