### ISSUE TITLE
Cntk Parser has not supported operator [Slice]

### ISSUE THREAD

**Issue by rasemailcz** [Microsoft/MMdnn#349]
Platform (like ubuntu 16.04/win10):
win10
Python version:
3.5
Source framework with version (like Tensorflow 1.4.1 with GPU):
CNTK-gpu 2.5.1
Destination framework with version (like CNTK 2.3 with GPU):
Keras 2.2.0

**Comment by namizzz** [comment]
Hi @rasemailcz ,MMdnn doesn't support it now. Here is [Contribution-Guideline](https://github.com/Microsoft/MMdnn/wiki/Contribution-Guideline) . You can try to implement it. Thanks!

**Comment by rasemailcz** [comment]
Hi @namizzz, I would love to do that, however getting familiar with the code costs time and I miss only "simple" tensor slicing. I presume that tensor concatenating, in ctnk "splicing" is also not supported - I could use that too. Is there any chance that I could motivate anyone who is familiar with the code to implement the "slice" and "splice"?

**Comment by namizzz** [comment]
Hi @rasemailcz , ok. Could you please provide the CNTK mode lfile?

**Comment by rasemailcz** [comment]
@namizzz thank you very much. I attach the [model file](https://github.com/Microsoft/MMdnn/files/2273788/network.zip). There is both slice [tensor slicing] and splice [tensor concatenating].

Please feel free to request from my PayPal account ras@email.cz

**Comment by rasemailcz** [comment]
@namizzz thanks...
