### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by SherlockBlaze** [Microsoft/MMdnn#356]
Hi there,
I read the code, and find a little thing that's maybe not worth mentioning.
I find the code in the file named IRToModel.
There's a statement in it.

    elif args.framework == 'cntk':
        raise NotImplementedError("Destination [Tensorflow] is not implemented yet.")

The "Tensorflow" may be "cntk" here.

**Comment by kitstar** [comment]
Fixed! Thanks for report it!
