### ISSUE TITLE
Tensorflow Fused Batchnorm to Pytorch?

### ISSUE THREAD

**Issue by Eyyub** [Microsoft/MMdnn#362]
Hi,

I'm currently trying to convert a custom ResNet18 from tensorflow to pytorch.
At the step of using `mmconvert` I ran into the following error:
```
IR network structure is saved as [ef6477f3b60b4424a909088cf082a038.json].
IR network structure is saved as [ef6477f3b60b4424a909088cf082a038.pb].
IR weights are saved as [ef6477f3b60b4424a909088cf082a038.npy].
Parse file [ef6477f3b60b4424a909088cf082a038.pb] with binary format successfully.
Target network code snippet is saved as [tf16.py].
Target weights are saved as [ef6477f3b60b4424a909088cf082a038.npy].
  File "/home/eyyub/mmdnn/venv/bin/mmconvert", line 11, in <module>
    sys.exit(_main())
  File "/home/eyyub/mmdnn/venv/local/lib/python2.7/site-packages/mmdnn/conversion/_script/convert.py", line 112, in _main
    dump_code(args.dstFramework, network_filename + '.py', temp_filename + '.npy', args.outputModel, args.dump_tag)
  File "/home/eyyub/mmdnn/venv/local/lib/python2.7/site-packages/mmdnn/conversion/_script/dump_code.py", line 32, in dump_code
    save_model(MainModel, network_filepath, weight_filepath, dump_filepath)
  File "/home/eyyub/mmdnn/venv/local/lib/python2.7/site-packages/mmdnn/conversion/pytorch/saver.py", line 5, in save_model
    model = MainModel.KitModel(weight_filepath)
  File "tf16.py", line 28, in __init__
    self.convolution_layer_block_layer1_batch_normalization_FusedBatchNorm = self.__batch_normalization(2, 'convolution_layer/block_layer1/batch_normalization/FusedBatchNorm', num_features=64, eps=0.0010000000475, momentum=0.0)
  File "tf16.py", line 173, in __batch_normalization
    layer.state_dict()['running_mean'].copy_(torch.from_numpy(__weights_dict[name]['mean']))
RuntimeError: The expanded size of the tensor (64) must match the existing size (0) at non-singleton dimension 0
```
I also got the same error (except for the tensor size) for a pretrained ResNet50 (not the one available in `mmdownload`. It seems to be related to FusedBatchnorm, I would like to know if mmdnn supports conversion of this op from tensorflow to pytorch and if it does, do you have any idea about where the issue could come from?

Thanks,

Platform (like ubuntu 16.04/win10):
Ubuntu 16.04

Python version:
2.7

Source framework with version (like Tensorflow 1.4.1 with GPU):
Tensorflow 1.8.0 GPU

Destination framework with version (like CNTK 2.3 with GPU):
Pytorch 0.4.0 (GPU)

Pre-trained model path (webpath or webdisk path):

Running scripts:
`mmconvert -sf tensorflow -iw resnet-18_train.pb --inNodeName "input_x" --inputShape 224,224,3 --dstNodeName "output/BiasAdd" -df pytorch -om tf16.pth
`

**Comment by Eyyub** [comment]
Hey @namizzz thank for so much to have fixed this issue so fast!

I'm sorry to ask again but after pulling the master and running the same command line I have the current runtime error 
```
  File "/usr/local/bin/mmconvert", line 9, in <module>
    load_entry_point('mmdnn==0.2.3', 'console_scripts', 'mmconvert')()
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convert.py", line 112, in _main
    dump_code(args.dstFramework, network_filename + '.py', temp_filename + '.npy', args.outputModel, args.dump_tag)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/dump_code.py", line 32, in dump_code
    save_model(MainModel, network_filepath, weight_filepath, dump_filepath)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/pytorch/saver.py", line 5, in save_model
    model = MainModel.KitModel(weight_filepath)
  File "tf16.py", line 28, in __init__
    self.convolution_layer_block_layer1_batch_normalization_FusedBatchNorm = self.__batch_normalization(2, 'convolution_layer/block_layer1/batch_normalization/FusedBatchNorm', num_features=64, eps=0.0010000000475, momentum=0.0)
  File "tf16.py", line 173, in __batch_normalization
    layer.state_dict()['running_mean'].copy_(torch.from_numpy(__weights_dict[name]['mean']))
RuntimeError: the given numpy array has zero-sized dimensions. Zero-sized dimensions are not supported in PyTorch 
```
If you think the error not because I did something wrong and that it is worth to create a new issue to not pollute this one please let me know!

Thanks

**Comment by namizzz** [comment]
Hi @Eyyub ,your running scripts is wrong, you need to add **-dw pytorch.npy**, because pytorch needs a converted weight file:

`
mmconvert -sf tensorflow -iw resnet-18_train.pb --inNodeName "input_x" --inputShape 224,224,3 --dstNodeName "output/BiasAdd" -df pytorch  -dw pytorch.npy -om tf16.pth -dw pytorch.npy
`

**Comment by Eyyub** [comment]
Hi @namizzz, sorry for disturbing again I tried using your command line and it didn't work :/
The model I'm trying to convert is the [ResNet50 v1 SavedModel](https://github.com/tensorflow/models/tree/master/official/resnet) that I froze. By any chance did you try to convert this one to pytorch?

**Comment by Eyyub** [comment]
Hi @namizzz, my bad! I did it but still have an issue, as I understand it is very hard for you to detect the issue without knowing the commands I used, I made a script to reproduce the error:

```bash
pip install -U git+https://github.com/Microsoft/MMdnn.git@master
mkdir /tmp/issue362 && cd /tmp/issue362
wget http://download.tensorflow.org/models/official/20180601_resnet_v1_imagenet_savedmodel.tar.gz
tar -xvf 20180601_resnet_v1_imagenet_savedmodel.tar.gz 
freeze_graph --input_saved_model_dir=20180601_resnet_v1_imagenet_savedmodel/1527888778 --output_graph=resnet50v1_frozen.pb --output_node_names="ArgMax,softmax_tensor"
mmconvert -sf tensorflow -iw resnet50v1_frozen.pb --inNodeName "input_tensor" --inputShape 224,224,3 --dstNodeName "softmax_tensor" -df pytorch -dw pytorch.npy -om resnet50v1.pth

```

**Comment by Eyyub** [comment]
Hi @namizzz, sorry to disturb again but do you have any about this issue?

**Comment by namizzz** [comment]
Hi @Eyyub , thanks for your issue, we have fixed it !

**Comment by Eyyub** [comment]
Hi @namizzz excellent it seems this particular issue was fixed I can convert it now! I have an other issue though but I will open a new issue to not pollute this one.

Thanks!
