### ISSUE TITLE
load pytorch vgg16 converted from tensorflow : ImportError: No module named 'MainModel'

### ISSUE THREAD

**Issue by Proxiaowen** [Microsoft/MMdnn#378]
Platform (like ubuntu 16.04/win10): ubuntu16

Python version:  3.6

Source framework with version (like Tensorflow 1.4.1 with GPU): 1.3

Destination framework with version (like CNTK 2.3 with GPU):

Pre-trained model path (webpath or webdisk path): 

Running scripts:
when torch.load have converted pretrain model
ImportError: No module named 'MainModel'

**Comment by namizzz** [comment]
Hi @Proxiaowen ,please refer to https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/examples/pytorch/imagenet_test.py#L22 .It's the right way to load a pytorch model code converted by mmdnn. Thanks!

**Comment by namizzz** [comment]
Hi @Proxiaowen ,  please refer to https://github.com/Microsoft/MMdnn/tree/master/mmdnn/conversion/pytorch#convert-models-from-ir-to-pytorch-code-snippet-and-weights . You need to get the converted model code file first. there is a KitModel. Here is the MainModel : https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/examples/imagenet_test.py#L239

**Comment by Pro-xiaowen** [comment]
Thanks!@namizzz
I have get the converted pytorch model from a tensorflow model using this one command:
mmconvert -sf tensorflow -in imagenet_vgg16.ckpt.meta -iw vgg_16.ckpt --dstNode MMdnn_Output -df pytorch -om tf_to_pytorch_vgg16.pth 
this converted modal with the name 'tf_to_pytorch_vgg16.pth'.
I want to load the converted pytorch modal

**Comment by Pro-xiaowen** [comment]
when i  load the converted pytorch modal using following code:
torch.load(tf_to_pytorch_vgg166.pth)
there are one error: ImportError: No module named 'MainModel' 

So, i want to your help ,Thanks!@namizzz

**Comment by namizzz** [comment]
Hi @Proxiaowen ,

```python

import torch
import imp
import numpy as np
MainModel = imp.load_source('MainModel', "tf_pytorch_vgg19.py")

the_model = torch.load("tf_pytorch_vgg19.pth")
the_model.eval()

x = np.random.random([224,224,3])
x = np.transpose(x, (2, 0, 1))
x = np.expand_dims(x, 0).copy()
data = torch.from_numpy(x)
data = torch.autograd.Variable(data, requires_grad = False).float()

predict = the_model(data)


```

**Comment by Proxiaowen** [comment]
thanks  @namizzz 
i have fixed this.

**Comment by Jimzhou82sub** [comment]
Hi, I encounter a problem,I followed the guide to convert the tensorflow's to the Pytorch's.but the Pytorch's result is not good, the file(.pth) is 400bytes,and when I loaded the file I found there are no values,
