### ISSUE TITLE
SeparableConv2D Layer of Keras Model Converted to Caffe   

### ISSUE THREAD

**Issue by urbaneman** [Microsoft/MMdnn#386]
My Keras model have SeparableConv2D layers, how can I converted this model to Caffe?
Did you add this layer to Caffe? If you did, what should I do to slove this problem?

**Comment by urbaneman** [comment]
Thanks, very much.

**Comment by namizzz** [comment]
Hi @urbaneman ,here is no implementation of SeparableConv2D in caffe except for third party, but it's a combine of depthwise convolution and 1x1 convulution. Maybe you can implement it by yourself. Here is the [Contribution-Guideline](https://github.com/Microsoft/MMdnn/wiki/Contribution-Guideline).Thanks!

**Comment by urbaneman** [comment]
@namizzz Thanks reply! 
Did you mean change the SeparableConv2D to depthwise convolution and 1*1 Conv2D in Keras, than train the new model. And using the new model convert to Caffe?
If not, may I success through this method?
Thanks!

**Comment by urbaneman** [comment]
Thank you very much, @namizzz . It is sucessful by this way.
