### ISSUE TITLE
IR weights order confusion

### ISSUE THREAD

**Issue by chenghaz** [Microsoft/MMdnn#394]
From the README.md, IR weights data is NHWC order. 

"[Note!] Currently the IR weights data is in NHWC (channel last) format."

But it seems like the conv2d weights for tensorflow is [filter_height, filter_width, in_channels, out_channels]

**Comment by namizzz** [comment]
Hi @chenghaz , yes! we design the MMdnn IR all in  NHWC (channel last) format at first. but now there are some conflict. We are also considering rebuilding IR.Thanks!
