### ISSUE TITLE
Padding issue: VALID instead of SAME

### ISSUE THREAD

**Issue by blagodurov** [Microsoft/MMdnn#397]
I am trying to run inference in TF with vgg19 and other models converted with mmdnn from caffe, but I see errors that stem from the padding tag being VALID. When I replace VALID with SAME, the errors go away, and the runs achieve their expected level of accuracy.

Here is how I generate the saved_model.pb:
mmdownload -f caffe -n vgg19 -o ./
mmconvert --srcFramework caffe --inputShape 3,224,224 --inputWeight ./vgg19.caffemodel --inputNetwork ./vgg19-deploy.prototxt --dstFramework tensorflow --outputModel vgg19-out --dump_tag SERVING > vgg19.log 2>&1

Here is how to check the padding tags:
import tensorflow as tf
with tf.Session(graph=tf.Graph()) as sess:
  tf.saved_model.loader.load(sess, [tf.saved_model.tag_constants.SERVING], "./caffe/convert/vgg19-out")
  graph_def = sess.graph.as_graph_def()
  node_names = [node.name for node in graph_def.node]
  node_paddings = [node.attr['padding'].s for node in graph_def.node]
  i=0
  for node_name in node_names:
    if node_paddings[i] != "":
      print node_name + " " + node_paddings[i]
    i+=1

The output is:
convolution VALID
convolution_1 VALID
pool1 VALID
convolution_2 VALID
convolution_3 VALID
pool2 VALID
convolution_4 VALID
convolution_5 VALID
convolution_6 VALID
convolution_7 VALID
pool3 VALID
convolution_8 VALID
convolution_9 VALID
convolution_10 VALID
convolution_11 VALID
pool4 VALID
convolution_12 VALID
convolution_13 VALID
convolution_14 VALID
convolution_15 VALID
pool5 VALID

This graph gives the errors when running similar to:
ValueError: Negative dimension size caused by subtracting 3 from 1 for 'conv16/Conv2D' (op: 'Conv2D') with input shapes: [1,1,1,512], [3,3,512,512].

Replacing VALID with SAME results in those errors go away, and the runs achieve their expected level of accuracy.

**Comment by namizzz** [comment]
Hi @blagodurov , I tried and didn't get error.Are you using the newest version MMdnn?

**Comment by blagodurov** [comment]
@namizzz What did you try? The conversion works ok for me too. The problem is that the converted .pb file contains wrong padding values: VALID. The right conversion should contain "SAME" padding, but mmdnn fails to do so.

**Comment by namizzz** [comment]
Hi @blagodurov , ok ,I understand! But have you ever check the converted model code file ? There are the code in it:
```python
data            = tf.placeholder(tf.float32, shape = (None, 224, 224, 3), name = 'data')
    conv1_1_pad     = tf.pad(data, paddings = [[0L, 0L], [1L, 1L], [1L, 1L], [0L, 0L]])
    conv1_1         = convolution(conv1_1_pad, group=1, strides=[1, 1], padding='VALID', name='conv1_1')
    relu1_1         = tf.nn.relu(conv1_1, name = 'relu1_1')
    conv1_2_pad     = tf.pad(relu1_1, paddings = [[0L, 0L], [1L, 1L], [1L, 1L], [0L, 0L]])
    conv1_2         = convolution(conv1_2_pad, group=1, strides=[1, 1], padding='VALID', name='conv1_2')
    relu1_2         = tf.nn.relu(conv1_2, name = 'relu1_2')
    pool1_pad       = tf.pad(relu1_2, paddings = [[0L, 0L], [0L, 1L], [0L, 1L], [0L, 0L]], constant_values=float('-Inf'))
    pool1           = tf.nn.max_pool(pool1_pad, [1, 2, 2, 1], [1, 2, 2, 1], padding='VALID', name='pool1')
    conv2_1_pad     = tf.pad(pool1, paddings = [[0L, 0L], [1L, 1L], [1L, 1L], [0L, 0L]])
    conv2_1         = convolution(conv2_1_pad, group=1, strides=[1, 1], padding='VALID', name='conv2_1')
    relu2_1         = tf.nn.relu(conv2_1, name = 'relu2_1')
```

I think you can understand why you get all layers in **valid** mode now. 

I said "I tried and didn't get error." means I didn't got "ValueError: Negative dimension size caused by subtracting 3 from 1 for 'conv16/Conv2D' (op: 'Conv2D') with input shapes: [1,1,1,512], [3,3,512,512]." Thanks !

**Comment by blagodurov** [comment]
Sorry, we thought that the padding for convolution nodes is being set in within-op padding value, and we initially skipped the ‘Pad’ node in the pb file. After incorporating info from the 'Pad' nodes, the error went away. Thank you for your help!
