### ISSUE TITLE
Shape incorrect when converting TensorFlow-->IR-->PyTorch

### ISSUE THREAD

**Issue by ZiangYan** [Microsoft/MMdnn#400]
For scripts and model files, please refer to #398 

Using your new commit #399 , I am not able to perform the converting, and I finally got a pytorch .py file together with a .npy model weight file.

I test the converted file with
```
model = KitModel('./converted_pytorch.npy')
x = torch.randn(5, 64, 64, 3)
y = model(x)
print y.shape
```
and got this error
```
Traceback (most recent call last):
  File "converted_pytorch.py", line 203, in <module>
    y = model(x)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "converted_pytorch.py", line 101, in forward
    add_2           = conv2d_8_Conv2D + conv2d_6_Conv2D
RuntimeError: The size of tensor a (62) must match the size of tensor b (64) at non-singleton dimension 2
```

The converted IR file and pytorch file is available at [here](https://drive.google.com/open?id=1WyFaM7hvLhudKbcClnmgqouRom_uArFd)

**Comment by namizzz** [comment]
Hi @ZiangYan , I searched your model and I know the problem! Please refer to this https://github.com/Microsoft/MMdnn/issues/379#issuecomment-416484025 . Now we are also thinking about the implementation of NCHW conversion. Thanks!

**Comment by ZiangYan** [comment]
Thanks @namizzz !
After I generate a NHWC tf model, everything works perfectly!!
