### ISSUE TITLE
Wrong handling of -1axis

### ISSUE THREAD

**Issue by justinboneh** [Microsoft/MMdnn#404]
https://github.com/Microsoft/MMdnn/blob/b00eb71dcc20b4cb240995198b1ec21c09964530/mmdnn/conversion/keras/keras2_parser.py#L364

`axis` is an integer, not a string. The condition is never met.

**Comment by namizzz** [comment]
Hi @justinboneh , we have fixed it ! You can try the newest version. Thanks!
