### ISSUE TITLE
Error when inception_v3 from tensorflow-IR convert to mxnet

### ISSUE THREAD

**Issue by mapicc** [Microsoft/MMdnn#41]
OS: CentOS7.0
tensorflow: 1.4.1
mxnet: 1.0.0

I download pre-train model from [inception_v3_2016_08_28.tar.gz](http://download.tensorflow.org/models/inception_v3_2016_08_28.tar.gz) 

I follow these steps:
1. Use python to extract both network architecture and weights
    `python -m mmdnn.conversion.examples.tensorflow.extract_model -n inception_v3 -ckpt ./inception_v3.ckpt`
2. Convert model (including architecture and weights) from Tensorflow to IR
    `python -m mmdnn.conversion._script.convertToIR -f tensorflow -d inception_v3 -n imagenet_inception_v3.ckpt.meta -w inception_v3.ckpt  --dstNodeName Squeeze`
3. Convert models from IR to MXNet code snippet and weights
    `python -m mmdnn.conversion._script.IRToCode -f mxnet --IRModelPath inception_v3.pb --dstModelPath mxnet_inception_v3.py --IRWeightPath inception_v3.npy -dw ./mxnet_inception_v3-0000.params`
4. Convert models from IR to MXNet checkpoint file
    `python -m mmdnn.conversion.examples.mxnet.imagenet_test -n mxnet_inception_v3 -w mxnet_inception_v3-0000.params --dump inception_v3`

Step 1-3 works well, but step 4 reports some warning:
`/usr/lib/python2.7/site-packages/mxnet/module/base_module.py:53: UserWarning: You created Module with Module(..., label_names=['softmax_label']) but input with name 'softmax_label' is not found in symbol.list_arguments(). Did you mean one of:
	input
  warnings.warn(msg)
/usr/lib/python2.7/site-packages/mxnet/module/base_module.py:65: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
MXNet checkpoint file is saved with prefix [inception_v3] and iteration 0, generated by [mxnet_inception_v3.py] and [mxnet_inception_v3-0000.params].`

After step 4, `inception_v3-symbol.json` and `inception_v3-0000.params` generated. When I test these file  using `sym, arg_params, aux_params = mx.model.load_checkpoint('inception_v3', 0)
mod = mx.mod.Module(symbol=sym, context=mx.cpu(), label_names=None)`, the error occurs:
`Traceback (most recent call last):
  File "inception_v3-loading.py", line 10, in <module>
    mod = mx.mod.Module(symbol=sym, context=mx.cpu(), label_names=None)
  File "/usr/lib/python2.7/site-packages/mxnet/module/module.py", line 93, in __init__
    _check_input_names(symbol, data_names, "data", True)
  File "/usr/lib/python2.7/site-packages/mxnet/module/base_module.py", line 51, in _check_input_names
    raise ValueError(msg)
ValueError: You created Module with Module(..., data_names=['data']) but input with name 'data' is not found in symbol.list_arguments(). Did you mean one of:
	input`

Could someone help me?

**Comment by SkyBiGZhou** [comment]
For MXNet Module API, `<mx.mod.Module>` has parameters `data_names` with default value `data` as its input layer. Actually, your input layer named `input` after converting from Tensorflow. So it cannot be detected.

Therefore, you should add this parameter while wrapping the Symbol. That is
`mod = mx.mod.Module(symbol = sym, context = mx.cpu(), data_names = ['input'], label_names = None)`

Also, the warning is caused by the same problem as softmax output is set as default, but actually it will not affect the performance.

**Comment by mapicc** [comment]
@SkyBiGZhou Thank you very much,  It works well now.
