### ISSUE TITLE
Convert Pytorch to IR, get a error, may be a bug

### ISSUE THREAD

**Issue by houkai** [Microsoft/MMdnn#414]
Platform (like ubuntu 16.04/win10):
Mac 10.13.6 (17G65) cpu
Python version: 2.7
Source framework with version (like Tensorflow 1.4.1 with GPU): pytorh
Command:
```
python -m mmdnn.conversion._script.convertToIR -f pytorch -n net.pth --inputShape 3,224,224 -d ket
```
Error:
TypeError: _jit_pass_onnx(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch::jit::Graph, arg1: torch._C._onnx.OperatorExportTypes) -> torch::jit::Graph
Error position:
https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/pytorch/pytorch_graph.py
```
64: def _optimize_graph(graph, aten, export_raw_ir=False):
...
124: trace.set_graph(PytorchGraph._optimize_graph(trace.graph(), False))
```
the param 'aten' is missing.

**Comment by houkai** [comment]
```
>>> torch.__version__
'0.4.1'
```
I fixed the above bug.
```
from torch.onnx import ONNX_ARCHIVE_MODEL_PROTO_NAME, ExportTypes, OperatorExportTypes
...
trace.set_graph(PytorchGraph._optimize_graph(trace.graph(), OperatorExportTypes.ONNX, False))
```
But occure othererror
```
ValueError: invalid literal for int() with base 10: '%204'
in: 
output_shape_str = re.findall(r'[^()!]+', node.__str__())[1]
output_shape = [int(x.replace('!', '')) for x in output_shape_str.split(',')]
```
some nodes in my pytorch model:
```
%203 : Float(1, 512, 7, 7) = onnx::Add(%202, %197), scope: ResNet/Sequential[layer4]/BasicBlock[1]
%205 : Dynamic = onnx::Pad[mode=constant, pads=[0, 0, 0, 0, 0, 0, 0, 0], value=0](%204), scope: ResNet/AvgPool2d[avgpool]
%209 : Long() = onnx::Squeeze[axes=[0]](%208), scope: ResNet
```
This program can only handle the first type!
I think mmdnn is Incompatible with my pytorch version. it may Incompatible with my model file.
I gave up.

**Comment by chenghaz** [comment]
Seems like MMdnn cannot handle %205 %209, when output shape is unknown.

**Comment by rainLiuplus** [comment]
Hi @houkai, currently mmdnn does not support pytorch 0.4.1 and the adaptation to version 0.4.1 is under development. Please use pytorch 0.4.0. Thanks！

**Comment by houkai** [comment]
@rainLiuplus Thanks!

**Comment by twmht** [comment]
@rainLiuplus 

when are you going to support 0.4.1?

**Comment by KeremTurgutlu** [comment]
It doesn't seem to suppport v1.0 is that correct?
