### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb7 in position 0: invalid start byte

### ISSUE THREAD

**Issue by meanmee** [Microsoft/MMdnn#42]
I just download the nasnet model, then run the command: python -m mmdnn.conversion._script.convertToIR -f tensorflow -d nasnet_large -n model.ckpt.data-00000-of-00001 --dstNodeName Squeeze

unlucky, an error just occurred:
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb7 in position 0: invalid start byte

**Comment by kitstar** [comment]
Could you provide full log and call stack? Is the tensorflow model loading problem?
