### ISSUE TITLE
Caffe->Tensorflow: Can we convert the saved_model.pb, .data and .variable file in one frozen pb ?

### ISSUE THREAD

**Issue by parth1595** [Microsoft/MMdnn#424]
I have converted caffe model to tensorflow model and three files where generated from that saved_model.pb, .data and .index file. I think SavedModelBuilder method would be used to generate this files. 

I would like to have only one .pb file a frozen file. Because here if I want to again convert this tensorflow model to caffe then I will need one frozen file that is .pb. So how this can be done. Can't we generate the frozen file using Saver method in this Or Convert this files into one frozen .pb file.

**Comment by namizzz** [comment]
Hi @parth1595 ,first, you can refer to [this ](https://github.com/Microsoft/MMdnn/tree/master/mmdnn/conversion/tensorflow#reuse-the-converted-tensorflow-model) to load your model, then freeze it. Thanks!

**Comment by doudasek** [comment]
@parth1595 I think I found solution here: https://github.com/Microsoft/MMdnn/issues/429#issuecomment-425183121

Please let me know if your converted model works correctly because mine is classifying wrong.

**Comment by parth1595** [comment]
@doudasek  Thanks it's working. I am successfully been able to convert the model using that script.
