### ISSUE TITLE
AssertionError: MMdnn_Output is not in graph

### ISSUE THREAD

**Issue by Archernarkiu** [Microsoft/MMdnn#428]
Platform (like ubuntu 16.04):

Python version:2.7

**Comment by qiqina** [comment]
I wonder how did you slove this problem? Thank you.

**Comment by rakeshramesha** [comment]
MMdnn_Output is supposed to be name of the output node. If you are using you own checkpoint (i.e not downloaded via mmdownload), then you have to replace it with an output node from your graph.

You can refer to the [TensorFlow to PyTorch tutorial](https://github.com/Microsoft/MMdnn/blob/master/docs/tf2pytorch.md).
Hope this helps.
