### ISSUE TITLE
how convert tranformer network model from tensorflow to pytorch ?

### ISSUE THREAD

**Issue by owenustc** [Microsoft/MMdnn#432]
Platform (like ubuntu 16.04/win10):

Python version: python2.7

Source framework with version (like Tensorflow 1.8 with GPU):

Destination framework with version (pytorch with GPU):

Pre-trained model path (transformer network model):

I want convert transformer, which is for NLP and not in MMdnn.extract_model.   How to add new network model supporting in MMdnn.

**Comment by kitstar** [comment]
Hi @owenustc  we are working on NLP models conversion and will ping you if there is any progress. Thanks!
