### ISSUE TITLE
 mmdnn.conversion.caffe.errors.ConversionError: Output shape computation not implemented for type: Split

### ISSUE THREAD

**Issue by plbmw** [Microsoft/MMdnn#433]
Platform (like ubuntu 16.04/win10):
win10
Python version:
3.6

Source framework with version (like Tensorflow 1.4.1 with GPU):
caffe 
Destination framework with version (like CNTK 2.3 with GPU):
Tensorflow 
Pre-trained model path (webpath or webdisk path):
https://drive.google.com/file/d/1mj2nqwN-woGlkq3rR24IT4GXsH47BSyY/view?usp=sharing
https://drive.google.com/file/d/1cgd3FawYwSI6DxeBodZCE-y9fqGd_B7h/view?usp=sharing
Running scripts:
mmconvert -sf caffe -in "C:\Users\Administrator\Desktop\Face Anti-spoofing\done\fake_face_0.prototxt" -iw "C:\Users\Administrator\Desktop\Face Anti-spoofing\done\fake_face_0.caffemodel" -df tensorflow -om tf_fake_face_0

**Comment by namizzz** [comment]
Hi @plbmw, I find there are two unimplemented layers "Split" and "Flatten". I infer the output shape and implement them. Is it right in the following?
![image](https://user-images.githubusercontent.com/11597267/46580731-21a48700-ca5d-11e8-98c9-09b1c41388a7.png)

I am not sure about the conversion of Split operator. I think we need to skip it? Please help me to see if it's right? Thanks!

**Comment by plbmw** [comment]
Hi @namizzz, Thanks for your answer, the shape is correct.  However it can not generate the shape pb file and last because that the split paramer missing, I modify a little as follow:

-  add praramter for split layer

```
    @classmethod
    def map_split(cls, node):
        kwargs = {'split': len(node.output), 'axis': 0}
        return Node.create('Split', **kwargs)
```

- modify axis for concat layer 

```
     @classmethod
    def map_concat(cls, node):
        # kwargs = {'axis': (2, 3, 1, 0)[node.parameters.axis]}
        kwargs = {'axis': node.parameters.axis}
        cls._convert_output_shape(kwargs, node)
        return Node.create('Concat', **kwargs)
```

Then I encounter  a new problem is the generate code can not generate the split index as below: 

if the code as bellow it will raise shape error. 
```
    pool3_pool3_0_split = tf.split(pool3, 2, 0, name='pool3_pool3_0_split')
    conv4           = convolution(pool3_pool3_0_split, group=1, strides=[1, 1], padding='VALID', name='conv4')
    flatten_pool3   = tf.contrib.layers.flatten(pool3_pool3_0_split)
```
I just want i like 
```
    pool3_pool3_0_split = tf.split(pool3, 2, 0, name='pool3_pool3_0_split')
    conv4           = convolution(pool3_pool3_0_split[0], group=1, strides=[1, 1], padding='VALID', name='conv4')
    flatten_pool3   = tf.contrib.layers.flatten(pool3_pool3_0_split[1])
```
I just do this manually, could solve this problem ?

**Comment by plbmw** [comment]
Thanks for you all, commit cdf4c95 can solve this issue.
