### ISSUE TITLE
Tensorflow Model UnicodeDecodeError

### ISSUE THREAD

**Issue by YanYas** [Microsoft/MMdnn#436]
Platform: Win8.1

Python version: 3.6

Source framework with version: Tensorflow 1.11.1 cpu

Destination framework with version: CNTK 2.6

Pre-trained model path: http://download.tensorflow.org/models/deeplabv3_pascal_train_aug_2018_01_04.tar.gz

Running scripts: python -m mmdnn.conversion._script.convertToIR -f tensorflow -n frozen_inference_graph.pb --dstNodeName ArgMax --inNodeName mul_1 --inputShape 299 299 3 -d deeplab

This returns an error:

> Info: Trying to parse file [frozen_inference_graph.pb] with binary format but failed with error [Error parsing message].
> Traceback (most recent call last):
>   File "C:\ProgramData\Miniconda3\envs\LookAtPytorch\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "C:\ProgramData\Miniconda3\envs\LookAtPytorch\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\ProgramData\Miniconda3\envs\LookAtPytorch\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 197, in <module>
>     _main()
>   File "C:\ProgramData\Miniconda3\envs\LookAtPytorch\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 192, in _main
>     ret = _convert(args)
>   File "C:\ProgramData\Miniconda3\envs\LookAtPytorch\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 66, in _convert
>     parser = TensorflowParser(args.network, args.weights, args.dstNodeName, inputshape[0], args.inNodeName)
>   File "C:\ProgramData\Miniconda3\envs\LookAtPytorch\lib\site-packages\mmdnn\conversion\tensorflow\tensorflow_parser.py", line 189, in __init__
>     model = TensorflowParser._load_meta(meta_file)
>   File "C:\ProgramData\Miniconda3\envs\LookAtPytorch\lib\site-packages\mmdnn\conversion\tensorflow\tensorflow_parser.py", line 84, in _load_meta
>     load_protobuf_from_file(meta_graph, model_network_path)
>   File "C:\ProgramData\Miniconda3\envs\LookAtPytorch\lib\site-packages\mmdnn\conversion\common\IR\IR_graph.py", line 28, in load_protobuf_from_file
>     text_format.Parse(file_content.decode('UTF-8'), container, allow_unknown_extension=True)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 0: invalid start byte
> 
Seems to work okay [here ](https://github.com/Microsoft/MMdnn/issues/121#issuecomment-389776521)

**Comment by YanYas** [comment]
Hi folks, any ideas?

**Comment by namizzz** [comment]
Hi @YanYas , if you want to use the frozen protobuf of tensorflow model file. Here are the [readme](https://github.com/Microsoft/MMdnn/tree/master/mmdnn/conversion/tensorflow#step-by-step-conversion-for-debugging). It's the right command:
`
python -m mmdnn.conversion._script.convertToIR -f tensorflow -w ./issue/deeplabv3_pascal_train_aug/frozen_inference_graph.pb --dstNodeName ArgMax --inNodeName mul_1 --inputShape 513,513,3 -d deeplab
`
You need to use `-w` to set the model file, not '-n'. and inputShape should in the format of `513,513,3` not '513 513 3'. Thanks!

**Comment by namizzz** [comment]
Hi @YanYas , please try the newest version.Thanks!
https://github.com/Microsoft/MMdnn#install-manually

**Comment by YanYas** [comment]
@namizzz Thanks that got it working. Sadly, and this is no fault of mmdnn, CNTK doesn't support some features found in Pytorch networks (Resizing), but thanks for your help :-)
