### ISSUE TITLE
Couldn't find enum DataType

### ISSUE THREAD

**Issue by ElegantGod** [Microsoft/MMdnn#465]
Platform (ubuntu 18.04):

Python version:python 2.7

Source framework with version (mxnet with GPU):

Destination framework with version (caffe with GPU):

Pre-trained model path (webpath or webdisk path):

Running scripts:
1) **mmconvert -sf mxnet -in vgg16-e2e-symbol.json -iw vgg16-e2e-0000.params -df caffe -om vgg16-e2e --inputShape 3,640,640**
or
2) **mmtoir -f mxnet -n vgg16-e2e-symbol.json -d vgg --inputShape 3,640,640**

 result:
**return _message.default_pool.FindEnumTypeByName(full_name)
KeyError: "Couldn't find enum DataType"**

**Comment by kitstar** [comment]
Hi @ElegantGod ,  seems your mxnet model contains some elements we didn't meet before. Is it an original mxnet model (not gluon)?

**Comment by ElegantGod** [comment]
Hi @kitstar ,it's the original mxnet installed from source v1.2.1.

**Comment by utkarsh-VRL** [comment]
@ElegantGod Did you find a solution to this problem?
Can you post it here for the benefit of all? thank you
