### ISSUE TITLE
why to get a `DummyData` layer when converting a standard `resnet-50` of mxnet to caffe

### ISSUE THREAD

**Issue by IvyGongoogle** [Microsoft/MMdnn#480]
hello, I use `mconvert -sf mxnet -in /xxx/resnet-50-symbol.json -iw /xxx/resnet-50-0000.params -df caffe -om resnet-50-symbol --inputShape 3,224,224` to convert a standard `resnet-50` of mxnet to caffe version, but why I get a `DummyData` layer?

`resnet-50-symbol.json` and  `resnet-50-0000.params` is [here](https://github.com/IvyGongoogle/resnet-protofiles/tree/master/mxnet/resnet-50).
can you give some advises?

**Comment by kitstar** [comment]
Hi @IvyGongoogle . Since the padding algorithm of Caffe is different from most frameworks, we try to pad more elements then use a DummyData to crop the output to get real shape. You can try to remove the related DummyData and Crop layers to see if it works.

Thanks.
