### ISSUE TITLE
How to convert tensorflow model after version 0.11 to Caffe?

### ISSUE THREAD

**Issue by Andy7mei** [Microsoft/MMdnn#492]
The usage of MMdnn that converting TF model to other format has options:
-in is used to specify the ".ckpt.meta" file.
-iw is used to specify the ".ckpt" file.
However, tensorflow model after version 0.11 has no .ckpt file, instead, it has .meta file, .data file, .index file.
What is the command line to convert tensorflow model after version 0.11 to Caffe?

**Comment by rainLiuplus** [comment]
Hi @Andy7mei , Please refer to this doc https://www.tensorflow.org/guide/saved_model. It said

> Note: There is not a physical file called /tmp/model.ckpt. It is the prefix of filenames created for the checkpoint. Users only interact with the prefix instead of physical checkpoint files.

**Comment by suikammd** [comment]
@rainLiuplus the link doesn't work

**Comment by rainLiuplus** [comment]
@suikammd 
You can try this tutorial l https://cv-tricks.com/tensorflow-tutorial/save-restore-tensorflow-models-quick-complete-tutorial/
