### ISSUE TITLE
ImportError: No module named contrib.keras.python.keras.preprocessing

### ISSUE THREAD

**Issue by seanchung2** [Microsoft/MMdnn#5]
I've install the MMdnn by executing this command `pip install https://github.com/Microsoft/MMdnn/releases/download/0.1.0/mmdnn-0.1.0-py2.py3-none-any.whl
`
And I've done these
```
$ wget http://download.tensorflow.org/models/resnet_v2_152_2017_04_14.tar.gz -P examples/tf/
$ tar -xvf examples/tf/inception_v3_2016_08_28.tar.gz
$ rm examples/tf/inception_v3_2016_08_28.tar.gz
$ mv *.ckpt *.graph examples/tf/
```
But the following error happened when I tried to run `python -m mmdnn.conversion.examples.tensorflow.extract_model -n resnet152 -ckpt examples/tf/resnet_v2_152.ckpt`
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/parallels/Desktop/CarML/MMdnn/mmdnn/conversion/examples/tensorflow/extract_model.py", line 12, in <module>
    from mmdnn.conversion.examples.imagenet_test import TestKit
  File "mmdnn/conversion/examples/imagenet_test.py", line 11, in <module>
    from tensorflow.contrib.keras.python.keras.preprocessing import image
ImportError: No module named contrib.keras.python.keras.preprocessing

```

Can you help me dealing with this? Thank you.

**Comment by kitstar** [comment]
Hi,

It is a absolute importing problem in Python2.7. Please update the pip package (name no changed) with:

pip install -U https://github.com/Microsoft/MMdnn/releases/download/0.1.0/mmdnn-0.1.0-py2.py3-none-any.whl

and try again. Thanks.

**Comment by seanchung2** [comment]
Thanks for prompt reply.

I tried to upgrade the package and the new error is:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/examples/tensorflow/extract_model.py", line 12, in <module>
    from mmdnn.conversion.examples.imagenet_test import TestKit
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/examples/imagenet_test.py", line 13, in <module>
    from tensorflow.contrib.keras.python.keras.preprocessing import image
ImportError: No module named python.keras.preprocessing
```

**Comment by kitstar** [comment]
What is your tensorflow version? 1.4? Checked the package of tensorflow in windows is different from in linux. Please update the pip package and try again. Thanks.

**Comment by seanchung2** [comment]
I used Linux so I'm pretty sure it is 1.4.0. I updated again and it remains...

**Comment by kitstar** [comment]
### Fixed problem
Hi, I fixed a api changed [tensorflow.contrib.keras.**python**.keras.preprocessing] --> tensorflow.contrib.keras.**api**.keras.preprocessing

And reinstalled tensorflow 1.4 and mmdnn (both with pip) but can't reproduce this problem.

### Question
If you pip package updated successfully, the error should become
[ImportError: No module named **api**.keras.preprocessing].

1. If error is is still [tensorflow.contrib.keras.**python**.keras.preprocessing]

Please check the file [~/.local/lib/python3.5/site-packages/**mmdnn/conversion/examples/imagenet_test.py**](my python library path, please change to your path) and see if there are lines like
```python
# work for tf 1.4 in windows & linux
from tensorflow.contrib.keras.api.keras.preprocessing import image
```
if it is just
```python
from tensorflow.contrib.keras.python.keras.preprocessing import image
```
which means the pip package is not updated. Please try this before re-install
```bash
pip uninstall mmdnn 
```

2. If the error is [No module named **api**.keras.preprocessing]

Please check if you can call
```bash
python -c "from tensorflow.contrib.keras.api.keras.preprocessing import image"
```

Thanks for diagnosing the problem.

**Comment by seanchung2** [comment]
The problem has been resolved. Thank you!
