### ISSUE TITLE
Support YOLOv2 from TensorFlow to Caffe?

### ISSUE THREAD

**Issue by ysh329** [Microsoft/MMdnn#51]
Thanks in advance. I found no YOLOv2 info. in readme.

**Comment by kitstar** [comment]
Hi @ysh329, Caffe emitter is in very early stage, only a small set of operators covered. Could you provide the YOLOv2 tensorflow model path for testing?
Thanks.

**Comment by ysh329** [comment]
@kitstar In fact, I wanna convert a YOLOv2 model trained using darknet to Caffe. However, I found some convertors from darknet to caffe are not supported completely or have some issues. Thus, I want to translate to popular TensorFlow model first then to Caffe 🤣 

I'm still trying convert darknet to tensorflow first but currently not happy🤣 Thanks for your relpy 🐰

**Comment by kitstar** [comment]
You are welcome. Plz ping me if you need any further help~

**Comment by ysh329** [comment]
@kitstar No problem 😀

**Comment by ahkarami** [comment]
Dear @kitstar & @ysh329,
There is a nice conversion of YOLOv2 in TensorFlow (_i.e.,_ [darkflow](https://github.com/thtrieu/darkflow)).
You can use it. However, I would be wonder how one can convert detection-based models from caffe to other frameworks (like TensorFlow or PyTorch) by using this nice repository (_i.e.,_ MMdnn).

**Comment by ysh329** [comment]
@ahkarami Thanks, I'll have a try~

**Comment by kitstar** [comment]
Hope someone can help the darknet -> IR part   :)

**Comment by namizzz** [comment]
@ahkarami  ,We have implemented the darknet -> IR part.Try the newest code,Thanks!
