### ISSUE TITLE
AssertionError: xxx is not in graph（multi_label_generate network）

### ISSUE THREAD

**Issue by 124399839** [Microsoft/MMdnn#514]
Platform (like ubuntu 16.04):

Python version:python2.7

Source framework with version (like Tensorflow 1.4 with CPU):

Running scripts:
mmconvert -sf tensorflow -in model.ckpt-600.meta -iw model.ckpt-600 --dstNodeName [fc20,fc21,fc22,fc23,fc24,fc25,fc26,fc27] -df caffe -om tf_mlp

I'm attempting to convert a TF model (multi_label_generate network) to caffe model.

### an AssertionError occured. this is the log:

`(project-P1jiVRWH) deep@server:~/project/test/test_model$ mmconvert -sf tensorflow -in model.ckpt-600.meta -iw model.ckpt-600 --dstNodeName [fc20,fc21,fc22,fc23,fc24,fc25,fc26,fc27] -df caffe -om tf_mlp
Parse file [model.ckpt-600.meta] with binary format successfully.
Tensorflow model file [model.ckpt-600.meta] loaded successfully.
Tensorflow checkpoint file [model.ckpt-600] loaded successfully. [352] variables loaded.
Traceback (most recent call last):
  File "/home/deep/.local/share/virtualenvs/project-P1jiVRWH/bin/mmconvert", line 11, in <module>
    sys.exit(_main())
  File "/home/deep/.local/share/virtualenvs/project-P1jiVRWH/local/lib/python2.7/site-packages/mmdnn/conversion/_script/convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "/home/deep/.local/share/virtualenvs/project-P1jiVRWH/local/lib/python2.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 68, in _convert
    parser = TensorflowParser(args.network, args.weights, args.dstNodeName)
  File "/home/deep/.local/share/virtualenvs/project-P1jiVRWH/local/lib/python2.7/site-packages/mmdnn/conversion/tensorflow/tensorflow_parser.py", line 221, in __init__
    model = extract_sub_graph(model, dest_nodes)
  File "/home/deep/.local/share/virtualenvs/project-P1jiVRWH/local/lib/python2.7/site-packages/tensorflow/python/framework/graph_util_impl.py", line 145, in extract_sub_graph
    assert d in name_to_node_map, "%s is not in graph" % d
AssertionError: [fc20,fc21,fc22,fc23,fc24,fc25,fc26,fc27] is not in graph`

### my  tf model code as follows：

`def model (images,keep_prob,is_training):
  

    with tf.variable_scope('conv1') as scope:
        omit
    # conv2
    with tf.variable_scope('conv2') as scope:
       omit
    with tf.variable_scope('max_pooling1') as scope:
        pool1 = tf.nn.max_pool(conv2,ksize = [1,2,2,1],strides= [1,2,2,1],padding='VALID',name='pooling1')
		omit
    #%%
    #conv3
    with tf.variable_scope('conv3') as scope:
       omit
    #conv4
    with tf.variable_scope('conv4') as scope:
       omit
    with tf.variable_scope('max_pooling2') as scope:
        pool2 = tf.nn.max_pool(conv4,ksize=[1,2,2,1],strides=[1,2,2,1],padding='VALID',name='pooling2')

    #conv5
    with tf.variable_scope('conv5') as scope:
       omit
    #conv6
    with tf.variable_scope('conv6') as scope:
       omit
    #pool3
    with tf.variable_scope('max_pool3') as scope:
         pool3 = tf.nn.max_pool(conv6,ksize=[1,2,2,1],strides=[1,2,2,1],padding='VALID',name='pool3')
    #%%
    #fc1_flatten
    with tf.variable_scope('fc1') as scope:
        shp = pool3.get_shape()
        flattened_shape =shp[1].value*shp[2].value*shp[3].value
        reshape = tf.reshape(pool3,[-1,flattened_shape])
    
    with tf.variable_scope('fc20') as scope:
        weights = tf.get_variable('weights',
                                  shape=[flattened_shape,2],
                                  dtype=tf.float32,
                                  initializer=tf.truncated_normal_initializer(stddev=0.005,dtype=tf.float32))
        biases = tf.get_variable('biases',
                                 shape=[2],
                                 dtype=tf.float32,
                                 initializer = tf.truncated_normal_initializer(0.1)
                                 )
        fc20 = tf.matmul(fc1,weights)+biases
	
	
    with tf.variable_scope('fc21') as scope:
        omit
    with tf.variable_scope('fc22') as scope:
        omit
    with tf.variable_scope('fc23') as scope:
        omit
    with tf.variable_scope('fc24') as scope:
        omit
    with tf.variable_scope('fc25') as scope:
       omit
    with tf.variable_scope('fc26') as scope:
       omit
    with tf.variable_scope('fc27') as scope:
        weights = tf.get_variable('weights',
                                  shape=[flattened_shape,36],
                                  dtype=tf.float32,
                                  initializer=tf.truncated_normal_initializer(stddev=0.005,dtype=tf.float32))

        biases = tf.get_variable('biases',
                                 shape=[36],
                                 dtype=tf.float32,
                                 initializer = tf.truncated_normal_initializer(0.1)
                                 )
        fc27 = tf.matmul(fc1,weights)+biases	

    return fc20,fc21,fc22,fc23,fc24,fc25,fc26,fc27   `

Do you know the reason? Thanks a lot!

**Comment by rainLiuplus** [comment]
Hi @124399839 , please put '' around the dstNodeName

**Comment by santosh-shriyan** [comment]
@rainLiuplus i tried your solution, the error still persist's .... although I have single output node and trying to convert it to pth file.
Hope you can help.
