### ISSUE TITLE
how to convert vggm from caffe to mxnet

### ISSUE THREAD

**Issue by renjiangyong** [Microsoft/MMdnn#52]
Hi, I have a question about how to convert vggm from caffe to mxnet, I have test the vgg19 and vgg16 can convert from caffe to mxnet successful, but the vggm doesn't work, the err is "axes don't match array"。I found that the MMdnn have test the vgg19 and googlenet . is this vggm supported？thank you.

**Comment by kitstar** [comment]
Hi @renjiangyong , could you provide the vggm model path for testing? Thanks.

**Comment by TobeyQin** [comment]
@renjiangyong could you give the vggm model url to me? I tried one from caffe model zoo (https://github.com/BVLC/caffe/wiki/Model-Zoo#models-used-by-the-vgg-team-in-ilsvrc-2014). It can convert successfully.
