### ISSUE TITLE
PRelu is not supported yet?

### ISSUE THREAD

**Issue by inkzk** [Microsoft/MMdnn#521]
Platform (like ubuntu 16.04/win10):
centos

Python version:
2.7

Source framework with version (like Tensorflow 1.4.1 with GPU):
caffe

Destination framework with version (like CNTK 2.3 with GPU):
pytorch0.4 with GPU

When I am trying to convert caffemodel to IR, error happens:
CntkEmitter has not supported operator [PRelu].

How should I deal with that?

**Comment by rainLiuplus** [comment]
https://github.com/Microsoft/MMdnn/issues/522
