### ISSUE TITLE
将保存了权重和网络结构的yolo3.h5模型转换为pb模型

### ISSUE THREAD

**Issue by Zev-Yin** [Microsoft/MMdnn#535]
https://github.com/qqwweee/keras-yolo3
请问用model.save保存了weights和net的yolo3.h5模型怎么转成pb模型？谢谢了

**Comment by rainLiuplus** [comment]
Hi @Zev-Yin , Thanks for your attention. Do you mean to transfer the model saved by keras to the tensorflow frozen model? If so, please refer to this link https://github.com/amir-abdi/keras_to_tensorflow
