### ISSUE TITLE
Support convert model of caffe-ssd to tensorflow's?

### ISSUE THREAD

**Issue by ysh329** [Microsoft/MMdnn#559]
Hi, all

1. I wanna convert ssd model from [weiliu89/caffe](https://github.com/weiliu89/caffe/tree/ssd) to tensorflow's. Does mmdnn support, or any todos?
2. Besides, does support ssd model conversion from tensorflow to caffe?

Thanks in advance.

**Comment by ysh329** [comment]
@rainLiuplus Thanks your reply.

**Comment by Bruce-GuoS** [comment]
> Hi @ysh329 , thanks for your attention, but we do not support ssd model conversion now. It is in our on-going list.

Hi, any process in convert ssd model from caffe to tensorflow?
Thanks in advance.
