### ISSUE TITLE
Temporary files are created under MMdnn root directory when running tests.

### ISSUE THREAD

**Issue by linmajia** [Microsoft/MMdnn#564]
Platform (like ubuntu win10):

Python version: 3.5.4

Source framework with version (like Tensorflow 1.9.0 with GPU):

Destination framework with version (like CNTK 2.3 with GPU):

Pre-trained model path (webpath or webdisk path):

Running scripts:
python tests\test_tensorflow.py

![image](https://user-images.githubusercontent.com/9329359/51092925-48025d00-17d8-11e9-8986-6aca90cb99c9.png)

**Comment by TobeyQin** [comment]
Fix on pull request #565
