### ISSUE TITLE
Convert_constant support in pytorch_parser.py?

### ISSUE THREAD

**Issue by irishjars** [Microsoft/MMdnn#578]
Hi,
Im trying to convert a Pytorch-based network im working on, to Keras. It fails because the onnx representation has onnx::constant.
Is there any branch that has this added?

**Comment by rainLiuplus** [comment]
Hi @irishjars , could you please give us more information? Thanks!

**Comment by irishjars** [comment]
Hi @rainLiuplus ,
I was facing a different issue as I've discovered. I've fixed the same.
Closing this issue as it was unrelated.
Thanks!
