### ISSUE TITLE
Multiple Outputs supporting

### ISSUE THREAD

**Issue by AIEternity** [Microsoft/MMdnn#580]
Platform (like ubuntu 16.04/win10):
win10
Python version:
3.5
Source framework with version (like Tensorflow 1.4.1 with GPU):
keras 2.2.4 with GPU
Destination framework with version (like CNTK 2.3 with GPU):
cntk 2.6
with GPU
Pre-trained model path (webpath or webdisk path):
[neuralnetwork2.zip](https://github.com/Microsoft/MMdnn/files/2828237/neuralnetwork2.zip)

Running scripts:
mmconvert -sf keras -iw neuralnetwork2.h5 -df cntk -om neuralnetwork3.dnn
Keras code:
```python
    inp = Input(shape=(200,))
    dense = Dense(2000,activation='relu')(inp)    
    dense2 = Dense(400,activation='relu')(dense) 
    dense3 = Dense(400,activation='relu')(dense)  
    model = Model(inputs=[inp], outputs=[dense2,dense3])
```

**Comment by rainLiuplus** [comment]
Hi @AIEternity ,

I converted your model and the result codes seems equal to the keras code. What's your problem? Thanks.

```
import numpy as np
import cntk
from cntk import ops, layers
from cntk.contrib.crosstalkcaffe.unimodel.cntkinstance import BlockApiSetup

__weights_dict = dict()

def load_weights(weight_file):
    if weight_file == None:
        return

    try:
        weights_dict = np.load(weight_file).item()
    except:
        weights_dict = np.load(weight_file, encoding='bytes').item()

    return weights_dict


def KitModel(weight_file = None):
    global __weights_dict
    __weights_dict = load_weights(weight_file)


    input_1         = cntk.sequence.input_variable((200,) , dtype = np.float32, name='input_1')
    dense_1         = dense(input_1, name = 'dense_1')
    dense_1_activation = layers.Activation(activation = ops.relu, name = 'dense_1_activation')(dense_1)
    dense_2         = dense(dense_1_activation, name = 'dense_2')
    dense_3         = dense(dense_1_activation, name = 'dense_3')
    dense_2_activation = layers.Activation(activation = ops.relu, name = 'dense_2_activation')(dense_2)
    dense_3_activation = layers.Activation(activation = ops.relu, name = 'dense_3_activation')(dense_3)
    return dense_2_activation,dense_3_activation


def dense(input, name, **kwargs):
    w = __weights_dict[name]['weights']
    b = __weights_dict[name]['bias'] if 'bias' in __weights_dict[name] else None
    return BlockApiSetup.linear(output_shape=w.shape[1], input_shape=w.shape[0], scale_init=w, bias_init=b, name=name, **kwargs)(input)
```

**Comment by AIEternity** [comment]
Hi, @rainLiuplus!
I use this command `mmconvert -sf keras -iw neuralnetwork2.h5 -df cntk -om neuralnetwork2.dnn`
And I get an Error:

>  IR network structure is saved as [2a3f9d661bc042319a5be60864a75724.json].
IR network structure is saved as [2a3f9d661bc042319a5be60864a75724.pb].
IR weights are saved as [2a3f9d661bc042319a5be60864a75724.npy].
Parse file [2a3f9d661bc042319a5be60864a75724.pb] with binary format successfully.
Target network code snippet is saved as [2a3f9d661bc042319a5be60864a75724.py].
Traceback (most recent call last):
  File "C:\Anaconda3\envs\cntk-py35\Scripts\mmconvert-script.py", line 11, in <module>
    load_entry_point('mmdnn==0.2.3', 'console_scripts', 'mmconvert')()
  File "C:\Anaconda3\envs\cntk-py35\lib\site-packages\mmdnn\conversion\_script\convert.py", line 112, in _main
    dump_code(args.dstFramework, network_filename + '.py', temp_filename + '.npy', args.outputModel, args.dump_tag)
  File "C:\Anaconda3\envs\cntk-py35\lib\site-packages\mmdnn\conversion\_script\dump_code.py", line 32, in dump_code
    save_model(MainModel, network_filepath, weight_filepath, dump_filepath)
  File "C:\Anaconda3\envs\cntk-py35\lib\site-packages\mmdnn\conversion\cntk\saver.py", line 3, in save_model
    model.save(dump_filepath)
AttributeError: 'tuple' object has no attribute 'save'

**Comment by rainLiuplus** [comment]
Hi @AIEternity , the model has two outputs, thus the `model` in [here](https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/cntk/saver.py#L2) is a tuple. Maybe you can manually modify the code to add the output subscript. Thanks!
