### ISSUE TITLE
How to convert tensorflow pb format to onnx?

### ISSUE THREAD

**Issue by xjcvip007** [Microsoft/MMdnn#585]
How to convert tensorflow pb format to onnx?

**Comment by rainLiuplus** [comment]
Hi @xjcvip007 , please refer to https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/tensorflow/README.md#frozen-graph-conversion

**Comment by xjcvip007** [comment]
@rainLiuplus ,Thanks for your quick reply, but it's tf to caffe in your link. I mean that convert tf pd format to onnx. Thx~

**Comment by rainLiuplus** [comment]
@xjcvip007 ,  to onnx just need to replace `-df caffe` to `-df onnx`, thanks!

**Comment by xjcvip007** [comment]
@rainLiuplus ,Thx~ Another question please, how about multiply inNodeName occur? Just split with comma?

**Comment by snehabhapkar10** [comment]
When I try to run this command
$ mmconvert -sf tensorflow -iw 20170512-110547.pb --inNodeName input,phase_train --dstNodeName embeddings -df onnx -om model

It gives an error
`KeyError: "The following input nodes were not found: {'input,phase_train'}"`

**Comment by romygt** [comment]
does anyone know how to convert tensorflow to onnx?? please I need help
