### ISSUE TITLE
ResNet V1  from tensoflow to caffe ?

### ISSUE THREAD

**Issue by LeeTaiTai** [Microsoft/MMdnn#589]
ResNet V1  How to convert from tensoflow to caffe ?

**Comment by rainLiuplus** [comment]
Hi @LeeTaiTai , please refer to https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/tensorflow/README.md#usage

**Comment by LeeTaiTai** [comment]
I  need  convert inception_resnet-v1 model from tensorflow to caffe,pls  help me

**Comment by rainLiuplus** [comment]
Duplicate with another issue, thus close this.
