### ISSUE TITLE
MMDNN Visualizer doesn't show layer config

### ISSUE THREAD

**Issue by drcege** [Microsoft/MMdnn#59]
Platform (like ubuntu 16.04/win10): `Ubuntu 16.04`

Python version: `3.5`

Source framework with version (like Tensorflow 1.4.1 with GPU): `Caffe`

Destination framework with version (like CNTK 2.3 with GPU): PyTorch

Pre-trained model path (webpath or webdisk path):  `https://gist.github.com/ksimonyan/a32c9063ec8e1118221a`

Running scripts:  `python -m mmdnn.conversion._script.convertToIR -f caffe -d vggF  -n VGG_CNN_F_deploy.prototxt -w VGG_CNN_F.caffemodel`

-----------------------

I converted VGG_CNN_F  model downloaded from Caffe Model Zoo to IR, then I upload vggF.json to MMdnn model visualizer  to get visualization. But the MMdnn model visualizer doesn't show any layer config, it seems to be the javascript issue.

 ```
draw.js:96 Uncaught TypeError: Cannot read property 'attr' of undefined
    at selectLayer (draw.js:96)
    at SVGRectElement.<anonymous> (draw.js:215)
    at SVGRectElement.<anonymous> (d3.v4.js:935)
```

**Comment by wangqianwen0418** [comment]
dear @drcege , can you upload your JSON file here? It will help me to reproduce this problem.

**Comment by drcege** [comment]
Github doesn't support JSON file type, so I added  **.log**

**Comment by drcege** [comment]
[vggF.json.log](https://github.com/Microsoft/MMdnn/files/1649609/vggF.json.log)

Github doesn't support JSON file type, so I added  **.log**

**Comment by wangqianwen0418** [comment]
@drcege, the bug has been fixed.
Thanks for your reporting
