### ISSUE TITLE
Pytorch to IR error:

### ISSUE THREAD

**Issue by HongChow** [Microsoft/MMdnn#602]
Platform:
ubuntu16.04. and I use the  mmdnn  docker environment(provided by https://github.com/Microsoft/MMdnn) .
I have check under python3 ,the torch version is 0.4.0 (in the docker container)
I am now trying to convert  pytorch to caffe. Before that, I should convert my pytorch (from pth file) to IR first, making the error as follows:
ValueError: invalid literal for int() with base 10: ...
And I also tried again using the downloaded model  as https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/pytorch/README.md shows
(1) mmdownload -f pytorch -n resnet18
(2) mmtoir -f pytorch -n   imagenet_resnet18.pth      --inputShape 3,224,224  -o  pytorch_resnet18_ir
and the same error  occurs:  
ValueError: invalid literal for int() with base 10: '3,224,224'

Could someone help me to handle this problem?

**Comment by HongChow** [comment]
supplement: mmdnn is installed by pip..

**Comment by HongChow** [comment]
I fix the problem by change the input format : --inputShape 3 224 224
while another errors coming:
(1) using the downloaded model resnet18 
AttributeError: 'collections.OrderedDict' object has no attribute 'state_dict'
(2) using another pth model : 
AttributeError: module 'torch._C' has no attribute '_cuda_getDevice'

**Comment by HongChow** [comment]
> I fix the problem by change the input format : --inputShape 3 224 224
> while another errors coming:
> (1)using the downloaded resnet18:
> AttributeError: 'collections.OrderedDict' object has no attribute 'state_dict'
> (2)using my own pth model :
> AttributeError: module 'torch._C' has no attribute '_cuda_getDevice'
for (2) , I motified the "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/pytorch/pytorch_parser.py" in docker :from 
model = torch.load(model_file_name) to 
model = torch.load(model_file_name,map_location='cpu') 
the "cuda  error " missed, while another  error happend:

Traceback (most recent call last):
  File "/usr/local/bin/mmtoir", line 11, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 184, in _main
    ret = _convert(args)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 79, in _convert
    parser = PytorchParser(args.network, inputshape)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/pytorch/pytorch_parser.py", line 71, in __init__
    model = torch.load(model_file_name,map_location='cpu')
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 476, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_is_real_file)
RuntimeError: unexpected EOF. The file might be corrupted.

Someting Wrong still exists when load the model?

**Comment by rainLiuplus** [comment]
Hi @HongChow , could you please provide your model for us to debug? Thanks.

**Comment by theFrenchDutch** [comment]
Hi, I'm also running into the 'dict' object has no attribute 'state_dict' issue (converting Pytorch to IR), so I figured I'd provide my model for debugging : 
https://ufile.io/d3piy

**Comment by HongChow** [comment]
@rainLiuplus great thanks . do you need pth file only or the python code? end How to send it to you ?

**Comment by rainLiuplus** [comment]
Hi @HongChow , I am sorry that the docker has not been updated in time. You can use pip to install mmdnn and then perform the conversion. I tried and it worked, thanks!

**Comment by HongChow** [comment]
@rainLiuplus  it's OK. Thank you.

**Comment by noending** [comment]
> I fix the problem by change the input format : --inputShape 3 224 224
> while another errors coming:
> (1)using the downloaded resnet18:
> AttributeError: 'collections.OrderedDict' object has no attribute 'state_dict'
> (2)using my own pth model :
> AttributeError: module 'torch._C' has no attribute '_cuda_getDevice'

Hi @HongChow , have you solved the question 2? i got same issue when i use my own squeezenet1_1  model pth.
