### ISSUE TITLE
How do I transfer from resnet50_v1.5 weight files to caffe, and do you have any plans to support it later?

### ISSUE THREAD

**Issue by huihuima** [Microsoft/MMdnn#606]
Platform (like ubuntu 16.04/win10):

Python version:

Source framework with version (like Tensorflow 1.4.1 with GPU):

Destination framework with version (like CNTK 2.3 with GPU):

Pre-trained model path (webpath or webdisk path):

Running scripts:

**Comment by rainLiuplus** [comment]
Hi @huihuima , you can follow the steps written in tensorflow README to have a try first. If there are any problems, feel free to reopen the issue. Thanks!
