### ISSUE TITLE
Tensorflow -> MXNet : 'softmax_label' is not found in symbol.list_arguments()

### ISSUE THREAD

**Issue by zchfaq** [Microsoft/MMdnn#614]
Platform (like ubuntu 16.04/win10):
ubuntu 16.04
Python version:
python 3.5
Source framework with version (like Tensorflow 1.4.1 with GPU):
tensorflow 1.12
Destination framework with version (like CNTK 2.3 with GPU):
mxnet 1.4.0
Pre-trained model path (webpath or webdisk path):
official mobilenet_v2 model form google
Running scripts:
mmconvert -sf tensorflow -iw mobilenet_v2_1.0_224_frozen.pb --inNodeName input --inputShape 224,224,3 --dstNodeName MobilenetV2/Predictions/Reshape_1 -df mxnet -om tf_mobile

/home/zch/.local/lib/python3.6/site-packages/mxnet/module/base_module.py:56: UserWarning: You created Module with Module(..., label_names=['softmax_label']) but input with name 'softmax_label' is not found in symbol.list_arguments(). Did you mean one of:
	Placeholder
  warnings.warn(msg)
/home/zch/.local/lib/python3.6/site-packages/mxnet/module/base_module.py:68: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
MXNet checkpoint file is saved with prefix [tf_mobilenet] and iteration 0, generated by [tf_mobilenet.py] and [tf_mobilenet.npy].

**Comment by rainLiuplus** [comment]
Hi @zchfaq , seems there are no errors and the warnings can be ignored. Thanks!
