### ISSUE TITLE
caffe转化成protch

### ISSUE THREAD

**Issue by lvpinrui** [microsoft/MMdnn#626]
python3.5.5
I0327 14:39:49.954829  3880 net.cpp:200] bn3a_branch1 does not need backward computation.
I0327 14:39:49.954829  3880 net.cpp:200] res3a_branch1 does not need backward computation.
I0327 14:39:49.954829  3880 net.cpp:200] res2c_res2c_relu_0_split does not need backward computation.
I0327 14:39:49.954829  3880 net.cpp:200] res2c_relu does not need backward computation.
I0327 14:39:49.954829  3880 net.cpp:200] res2c does not need backward computation.
I0327 14:39:49.954829  3880 net.cpp:200] scale2c_branch2c does not need backward computation.
I0327 14:39:49.954829  3880 net.cpp:200] bn2c_branch2c does not need backward computation.
I0327 14:39:49.954829  3880 net.cpp:200] res2c_branch2c does not need backward computation.
I0327 14:39:49.954829  3880 net.cpp:200] res2c_branch2b_relu does not need backward computation.
I0327 14:39:49.954829  3880 net.cpp:200] scale2c_branch2b does not need backward computation.
I0327 14:39:49.954829  3880 net.cpp:200] bn2c_branch2b does not need backward computation.
I0327 14:39:49.954829  3880 net.cpp:200] res2c_branch2b does not need backward computation.
I0327 14:39:49.954829  3880 net.cpp:200] res2c_branch2a_relu does not need backward computation.
I0327 14:39:49.954829  3880 net.cpp:200] scale2c_branch2a does not need backward computation.
I0327 14:39:49.954829  3880 net.cpp:200] bn2c_branch2a does not need backward computation.
I0327 14:39:49.954829  3880 net.cpp:200] res2c_branch2a does not need backward computation.
I0327 14:39:49.954829  3880 net.cpp:200] res2b_res2b_relu_0_split does not need backward computation.
I0327 14:39:49.954829  3880 net.cpp:200] res2b_relu does not need backward computation.
I0327 14:39:49.954829  3880 net.cpp:200] res2b does not need backward computation.
I0327 14:39:49.954829  3880 net.cpp:200] scale2b_branch2c does not need backward computation.
I0327 14:39:49.955827  3880 net.cpp:200] bn2b_branch2c does not need backward computation.
I0327 14:39:49.955827  3880 net.cpp:200] res2b_branch2c does not need backward computation.
I0327 14:39:49.955827  3880 net.cpp:200] res2b_branch2b_relu does not need backward computation.
I0327 14:39:49.955827  3880 net.cpp:200] scale2b_branch2b does not need backward computation.
I0327 14:39:49.955827  3880 net.cpp:200] bn2b_branch2b does not need backward computation.
I0327 14:39:49.955827  3880 net.cpp:200] res2b_branch2b does not need backward computation.
I0327 14:39:49.955827  3880 net.cpp:200] res2b_branch2a_relu does not need backward computation.
I0327 14:39:49.955827  3880 net.cpp:200] scale2b_branch2a does not need backward computation.
I0327 14:39:49.955827  3880 net.cpp:200] bn2b_branch2a does not need backward computation.
I0327 14:39:49.955827  3880 net.cpp:200] res2b_branch2a does not need backward computation.
I0327 14:39:49.955827  3880 net.cpp:200] res2a_res2a_relu_0_split does not need backward computation.
I0327 14:39:49.955827  3880 net.cpp:200] res2a_relu does not need backward computation.
I0327 14:39:49.956825  3880 net.cpp:200] res2a does not need backward computation.
I0327 14:39:49.956825  3880 net.cpp:200] scale2a_branch2c does not need backward computation.
I0327 14:39:49.956825  3880 net.cpp:200] bn2a_branch2c does not need backward computation.
I0327 14:39:49.956825  3880 net.cpp:200] res2a_branch2c does not need backward computation.
I0327 14:39:49.956825  3880 net.cpp:200] res2a_branch2b_relu does not need backward computation.
I0327 14:39:49.956825  3880 net.cpp:200] scale2a_branch2b does not need backward computation.
I0327 14:39:49.956825  3880 net.cpp:200] bn2a_branch2b does not need backward computation.
I0327 14:39:49.956825  3880 net.cpp:200] res2a_branch2b does not need backward computation.
I0327 14:39:49.956825  3880 net.cpp:200] res2a_branch2a_relu does not need backward computation.
I0327 14:39:49.956825  3880 net.cpp:200] scale2a_branch2a does not need backward computation.
I0327 14:39:49.956825  3880 net.cpp:200] bn2a_branch2a does not need backward computation.
I0327 14:39:49.956825  3880 net.cpp:200] res2a_branch2a does not need backward computation.
I0327 14:39:49.956825  3880 net.cpp:200] scale2a_branch1 does not need backward computation.
I0327 14:39:49.956825  3880 net.cpp:200] bn2a_branch1 does not need backward computation.
I0327 14:39:49.956825  3880 net.cpp:200] res2a_branch1 does not need backward computation.
I0327 14:39:49.956825  3880 net.cpp:200] pool1_pool1_0_split does not need backward computation.
I0327 14:39:49.956825  3880 net.cpp:200] pool1 does not need backward computation.
I0327 14:39:49.956825  3880 net.cpp:200] conv1_relu does not need backward computation.
I0327 14:39:49.956825  3880 net.cpp:200] scale_conv1 does not need backward computation.
I0327 14:39:49.956825  3880 net.cpp:200] bn_conv1 does not need backward computation.
I0327 14:39:49.956825  3880 net.cpp:200] conv1 does not need backward computation.
I0327 14:39:49.956825  3880 net.cpp:200] input does not need backward computation.
I0327 14:39:49.956825  3880 net.cpp:242] This network produces output prob
I0327 14:39:49.957823  3880 net.cpp:255] Network initialization done.
F0327 14:39:51.120713  3880 upgrade_proto.cpp:95] Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: resnet152.caffemodel
*** Check failure stack trace: ***

**Comment by rainLiuplus** [comment]
Hi @lvpinrui, I tried to convert resnet152 from Caffe to Pytorch locally and it seems ok. Maybe you can try again or give us more information?
