### ISSUE TITLE
Converting trained Object Detection PyTorch Darknet model to Tensorflow

### ISSUE THREAD

**Issue by buroa** [microsoft/MMdnn#633]
Platform (like ubuntu 16.04/win10): centos7

Python version: 3.6

Source framework with version (like Tensorflow 1.4.1 with GPU): PyTorch 1.0

Destination framework with version (like CNTK 2.3 with GPU): Tensorflow GPU

Pre-trained model path (webpath or webdisk path): https://storage.googleapis.com/ultralytics/xview_best_lite.pt

Running scripts:

Editing conversion/pytorch/pytorch_parser.py and loading the model like so:

```
cfg = './xview-yolov3/cfg/c60_a30symmetric.cfg'
            model = Darknet(cfg, 32 * 51)
            checkpoint = torch.load('xview_best_lite.pt', map_location='cpu')
            model.load_state_dict(checkpoint['model'], strict = False)
```

Then running

```mmconvert -sf pytorch -iw ./xview_best_lite.pt -df tensorflow -om ./xview.pb --inputShape 3,1632,1632```

Yields

```RuntimeError: /opt/conda/conda-bld/pytorch_1524584710464/work/torch/csrc/jit/tracer.h:120: getTracingState: Assertion `state` failed.```

**Comment by buroa** [comment]
I'm basically trying to use the exported xview.pb to do inference like this:

```def predict(self, images, model, session):
        boxes, scores, classes = [], [], []

        def tensor(t):
            return session.graph.get_tensor_by_name('{}/{}:0'.format(model, t))

        image_tensor = tensor('image_tensor')
        box_t, score_t, cls_t, detections_t = tensor('detection_boxes'), tensor('detection_scores'), \
                                              tensor('detection_classes'), tensor('num_detections')

        image = np.expand_dims(image, axis = 0)

        (box, score, cls, detections) = session.run(
            [box_t, score_t, cls_t, detections_t],
            feed_dict = {image_tensor: image})

        return np.squeeze(box), np.squeeze(score), np.squeeze(cls)```

**Comment by JiahaoYao** [comment]
Hi, @buroa probably because of the issue of https://github.com/pytorch/pytorch/issues/8473. I do look far into the problem, and maybe you can check your version of pytorch.

**Comment by buroa** [comment]
> Hi, @buroa probably because of the issue of [pytorch/pytorch#8473](https://github.com/pytorch/pytorch/issues/8473). I do look far into the problem, and maybe you can check your version of pytorch.

I have switched between so many different versions to get this to work ... I would just like to know how I can convert that model to do Tensorflow object detection.

**Comment by JiahaoYao** [comment]
I mean if the error is about `RuntimeError: /opt/conda/conda-bld/pytorch_1524584710464/work/torch/csrc/jit/tracer.h:120: getTracingState: Assertion `state` failed.`, this is about the error reported from `torch.jit`. Thus, I do not know what happened where the model is passed through mmdnn.
