### ISSUE TITLE
Tutorial for Converting MXNet Model to PyTorch

### ISSUE THREAD

**Issue by ahkarami** [microsoft/MMdnn#651]
Dear @rainLiuplus, @kitstar,
There is a great [tutorial](https://blog.paperspace.com/convert-full-imagenet-pre-trained-model-from-mxnet-to-pytorch/) for converting Full ImageNet pre-trained model from MXNet to PyTorch. I suggest to add it in the Tutorial section (or example section) of the README of the repository.

**Comment by linmajia** [comment]
@ahkarami , thank you very much for the information. We will contact the author for linking this great tutorial.

**Comment by linmajia** [comment]
We have added it in the "Users' Examples" section (the second link) of README. Thanks for the great tutorial!
