### ISSUE TITLE
Convert resnet50_v1 MXnet to IR

### ISSUE THREAD

**Issue by CarlosE97** [microsoft/MMdnn#655]
Hello, I'm trying to convert from ResNet50_v1 to the IR using this command:
------------------------------------------------------------------------------------

`mmtoir -f mxnet -n resnet-50-symbol.json -w resnet50_v1-0000.params -d resnet50v1 --inputShape 3 224 224`

But I'm getting this error:
----------------------------

> /usr/local/lib/python3.5/dist-packages/mxnet/module/base_module.py:56: UserWarning: You created Module with Module(..., label_names=['softmax_label']) but input with name 'softmax_label' is not found in symbol.list_arguments(). Did you mean one of:
>         data
>   warnings.warn(msg)
> Warning: MXNet Parser has not supported operator null with name data.
> Warning: convert the null operator with name [data] into input layer.
> Traceback (most recent call last):
>   File "/usr/local/bin/mmtoir", line 11, in <module>
>     sys.exit(_main())
>   File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 184, in _main
>     ret = _convert(args)
>   File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 102, in _convert
>     parser.run(args.dstPath)
>   File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/common/DataStructure/parser.py", line 22, in run
>     self.gen_IR()
>   File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 262, in gen_IR
>     func(current_node)
>   File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 515, in rename_BatchNorm
>     IR_node.attr["axis"].i = MXNetParser._convert_axis(IR_node, int(source_node.get_attr("axis", "1")))
>   File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 79, in _convert_axis
>     ndim = len(IR_node.attr['_output_shapes'].list.shape[0].dim)
> IndexError: list index out of range

If anyone has any solution for this problem, I would be delighted. Thank you

**Comment by rainLiuplus** [comment]
Hi @CarlosE97, could you please upload your model?

**Comment by CarlosE97** [comment]
Hello @rainLiuplus, thank you for your reply.
Here is the JSON file containing the model's architecture.

[resnet50_v1-symbol.zip](https://github.com/microsoft/MMdnn/files/3178018/resnet50_v1-symbol.zip)

Thanks.

**Comment by CarlosE97** [comment]
Hello @rainLiuplus, after updating MMdnn, this error was fixed and I got another error which was similar to issue #208. Thank you
