### ISSUE TITLE
How to convert Mxnet to Caffe?

### ISSUE THREAD

**Issue by tzhang2014** [Microsoft/MMdnn#66]
Hi, I want to convert Mxnet model to caffemodel , my Mxnet is v0.9.3. How can I do it ?Thx

**Comment by TobeyQin** [comment]
You should first convert mxnet pre-trained model to IR(see [here](https://github.com/Microsoft/MMdnn/tree/master/mmdnn/conversion/mxnet)), and then convert IR to caffe.

I will take resnet152 model as an example:
1. Convert mxnet to IR:
python -m mmdnn.conversion._script.convertToIR -f mxnet -n mxnet/models/resnet-152-symbol.json -w mxnet/models/resnet-152-0000.params -d resnet152 --inputShape 3 224 224

2. Convert IR to caffe code:
python -m mmdnn.conversion._script.IRToCode.py -f caffe -n resnet152.pb -w resnet152.npy -d caffe_resnet152.py -dw caffe_resnet152.npy

3. Generate caffe model from code:
python caffe_resnet152.py -w caffe_resnet152.npy -p resnet152.prototxt -m resnet152.caffemodel

Hope this can help solve your question. Currently, from IR to caffe is under initial state, we haven't done enough test, if there is any issue when you use it, welcome to report.

**Comment by tzhang2014** [comment]
thx , I have run the above example,  when I run the first command , Loadiing I met three warnings: 1.MXNet Parser has not supported operator num with name data. 2. convert the null operator with name [data] into tnput layer. 3. SoftmaxOutput attrs are not supported in IR.  So, When I run the second  command ,I met a error that printf("=======current_node=======\n{}".format(current_node.layer),file=f)  
SyntaxError: invalid syntax .
![2018-02-08 16-32-38](https://user-images.githubusercontent.com/19585245/35962990-4a0054fe-0cee-11e8-9dae-6bc94af166c5.png)

**Comment by kitstar** [comment]
Hi @tzhang2014 ,
Fixed. Please check the new module, Thanks.

**Comment by gunasekaran7** [comment]
I am trying to convert from IR to Caffe. And I am getting the following error. Any help would be appreciated.
![to_gh](https://user-images.githubusercontent.com/13835289/36722694-3b27bbb2-1bd4-11e8-9fd7-0e21e3e8e74e.png)

**Comment by kitstar** [comment]
Hi @gunasekaran7 , looks like there are some problem on Caffe Environment. Could you check it?
