### ISSUE TITLE
A way of convert tensorflow with  tf.train.exponential_decay to caffe

### ISSUE THREAD

**Issue by 2h4dl** [microsoft/MMdnn#670]
When we use exponential moving decay and restore it like below:
```
        ema = tf.train.ExponentialMovingAverage(0.999)
        ema_restore = ema.variables_to_restore()
        saver = tf.train.Saver(var_list=ema_restore)
```
Tensorflow will  use the moving average variable name as the restore name; otherwise, use the variable name. 

But  `tensorflow_parser.py` can't parser moving average variable by tensor name when 'set_weight', some small change can be mode to help this.
In method `_load_weights`, 
```
def _load_weights(model_weight_path):
        reader = tensorflow.train.NewCheckpointReader(model_weight_path)
        var_to_shape_map = reader.get_variable_to_shape_map()
        data = dict()
        for name in var_to_shape_map:
            tensor = reader.get_tensor(name)

            #===== Added code=====
            name_seg = name.split("/")
            if name_seg[-1] == "ExponentialMovingAverage":
                name = "/".join(name_seg[:-1])
            #===== Added code=====

            data[name] = tensor
        print ("Tensorflow checkpoint file [%s] loaded successfully. [%d] variables loaded." % (model_weight_path, len(data)))
        return data
```

May this small change will help you.

**Comment by rainLiuplus** [comment]
Hi @2h4dl, thanks for your advice! Maybe you could make a pr to submit these modifications. Thanks!

**Comment by 2h4dl** [comment]
> Hi @2h4dl, thanks for your advice! Maybe you could make a pr to submit these modifications. Thanks!

Which branch should I make a PR?

**Comment by rainLiuplus** [comment]
@2h4dl, master. Thanks!
