### ISSUE TITLE
pytorch->IR

### ISSUE THREAD

**Issue by huanyuan54** [microsoft/MMdnn#677]
Platform (like ubuntu 16.04/win10): ubuntu 16.04/

Python version: 2.7.13

mmdnn version:0.2.4

pytorch :0.4.0

Running scripts:
mmtoir -f pytorch -d resnet101 --inputShape 3,224,224 -n imagenet_resnet101.pth

AttributeError: 'module' object has no attribute '_rebuild_parameter'？

**Comment by rainLiuplus** [comment]
Maye you could downgrade torchvision to 0.2.1 and use the resnet101 of this version to try again. Thanks.

**Comment by huanyuan54** [comment]
@rainLiuplus  I use torchvision is 0.2.1 ，
resnet101 is Running scripts:
mmdownload -f pytorch -n resnet101 -o ./

**Comment by huanyuan54** [comment]
@rainLiuplus I downloaded the model again and the problem disappeared. Thank you very much！
