### ISSUE TITLE
Can this tool convert mxnet detection models to IR,  or more specifically Caffe?

### ISSUE THREAD

**Issue by TriLoo** [microsoft/MMdnn#680]
Hi, 

  I found that the current version mmdnn cannot convert detection models, like mobilenet ssd, from mxnet to IR or Caffe, because `MultiBoxPrior` (_contrib) operator from mxnet is not supported yet. No `MultiBoxPrior` convertion funcs are found in `mxnet_parse.py` as well.  Is it correct?

git hash: `d7e40c48e3f`

**Comment by rainLiuplus** [comment]
Yes, you are right.
