### ISSUE TITLE
MXNet Emitter has not supported operator [MatMul]

### ISSUE THREAD

**Issue by sy-swjtu** [microsoft/MMdnn#702]
Platform (win10):

Python version:3.6.3

Source framework with version (Tensorflow 1.4.0 with CPU):

Destination framework with version (Mxnet 1.4.1 with CPU):

Pre-trained model as follows
[mnist_matmul.zip](https://github.com/microsoft/MMdnn/files/3434538/mnist_matmul.zip)

1,mmtoir -f tensorflow -w D:\mnist\mnist_model_graph.pb --inNodeName input --inputShape 28,28,1 --dstNodeName output -o D:\mnist\ir
IR network structure is saved as [D:\mnist\ir.json].
IR network structure is saved as [D:\mnist\ir.pb].
IR weights are saved as [D:\mnist\ir.npy].

2,mmtocode -f mxnet -n D:\mnist\ir.pb -w D:\mnist\ir.npy -o D:\mnist\mxnet\mxnet.py -ow D:\mnist\mxnet\mxnet.npy
Parse file [D:\mnist\ir.pb] with binary format successfully.
Warning: Graph Construct a self-loop node BD1. Ignored.
Warning: Graph Construct a self-loop node B_OUT. Ignored.
Detect input layer [Placeholder] using infer batch size, set it as default value [1]
MXNet Emitter has not supported operator [MatMul].
MatMul
MXNet Emitter has not supported operator [MatMul].
MatMul_1
Target network code snippet is saved as [D:\mnist\mxnet\mxnet.py].

This problem occurs in the second step of model conversion，How to solve this problem，
Official documents have been consulted https://github.com/Microsoft/MMdnn/wiki/Contribution-Guideline 
I still don't understand how to do this.
Can you provide detailed steps for this problem?
Thank you，

**Comment by rainLiuplus** [comment]
Hi @sy-swjtu 

There are two methods to add [MatMul] in mxnet emitter:

1.  Directly add [MatMul] in mxnet_emitter.

     a. Find the corresponding [MatMul] op in mxnet. We search the mxnet doc and find that [mx.sym.batch_dot](https://mxnet.incubator.apache.org/api/python/symbol/symbol.html?highlight=batch#mxnet.symbol.batch_dot) is the operator with the closest semantics to [MatMul] but it only supports 3D array. Therefore, in order to remedy this problem, if the tensor rank is greater than 3, we can first reshape the tensor into a 3D array then perform batch_dot and last reshape it back. Otherwise, if the tensor rank equals 2, the [MatMul] can be replaced with [mx.sym.dot](https://mxnet.incubator.apache.org/api/python/symbol/symbol.html?highlight=dot#mxnet.symbol.dot). Additionally, mxnet does not possess [constant] op thus we need to register a custom constant op like [this](https://github.com/apache/incubator-mxnet/issues/6087#issuecomment-303364369).

    b. Edit mxnet_emitter.py to add [MatMul] by creating emit_MatMul function. (**Note** that this is just an example and I have not tested it.)
```
    def emit_MatMul(self, IR_node):
        rank = len(IR_node.get_attr('_output_shape').list.shape[0].dim)
        if rank == 2:
            weights_code = "mx.sym.Variable('{}', shape=self.weights[IR_node.name].shape, init=MyConstant(value=self.weights[IR_node.name]))".format(
                IR_node.name + '_weight'
            )
            code = "{:<15} = mx.sym.dot({}, {}, name='{}')".format(
                IR_node.variable_name, # current op's name
                self.parent_variable_name(IR_node), # parent op's name
                weights_code,
                IR_node.name
            )
            return code
        elif rank == 3:
            weights_code = "mx.sym.Variable('{}', shape=self.weights[IR_node.name].shape, init=MyConstant(value=self.weights[IR_node.name]))".format(
                IR_node.name + '_weight'
            )
            code = "{:<15} = mx.sym.batch_dot({}, {}, name='{}')".format(
                IR_node.variable_name, # current op's name
                self.parent_variable_name(IR_node), # parent op's name
                weights_code,
                IR_node.name
            )
            return code
        elif rank > 3:
            output_shape = IR_node.get_attr('_output_shape').list.shape.dim
            weight_shape = self.weights[IR_node.name].shape
            
            # reshape the input tensor and weights
            before_reshape= "{:<15} = mx.sym.reshape({}, shape=(-1, {}, {}), name='{}')".format(
                IR_node.variable_name,
                self.parent_variable_name(IR_node),
                str(output_shape[-2]),
                str(weight_shape[-2]),
                IR_node.name
            )
            self.weights[IR_node.name] = np.reshape(self.weights[IR_node.name], shape=(-1, weight_shape[-2], weight_shape[-1]))
            
            weights_code = "mx.sym.Variable('{}', shape=self.weights[IR_node.name].shape, init=MyConstant(value=self.weights[IR_node.name]))".format(
                IR_node.name + '_weight'
            )
            code = "{:<15} = mx.sym.batch_dot({}, {}, name='{}')".format(
                IR_node.variable_name, # current op's name
                self.parent_variable_name(IR_node), # parent op's name
                weights_code,
                IR_node.name
            )
            # reshape the output tensor back
            after_reshape = "{:<15} = mx.sym.reshape({}, shape=({}), name='{}')".format(
                IR_node.variable_name,
                self.parent_variable_name(IR_node),
                str(', '.join(output_shape)),
                IR_node.name
            )
            return [before_reshape, code, after_reshape]
        else:
            raise ValueError('xxx')
```

2. Fold this [MatMul] op into [FullyConnected] op.
    change [this line](https://github.com/microsoft/MMdnn/blob/master/mmdnn/conversion/tensorflow/tensorflow_frozenparser.py#L942) into  `if source_node.out_edges and self.tf_graph.get_node(source_node.out_edges[0]).type in ('BiasAdd', 'Add'):`. Then the [MatMul] op will be integrated into the [FullyConnected] op thus we could skip the implementation of [MatMul].


Last, there still exists the data format issue. For the current model, just remove the converted reshape op in your generated file mxnet.py.  Thanks!

**Comment by sy-swjtu** [comment]
Hi @rainLiuplus 
Thx for your help,It works!
