### ISSUE TITLE
torch to caffe

### ISSUE THREAD

**Issue by Gaochunyang1314** [microsoft/MMdnn#703]
how to write rename_deconv in pytorch_parser.py and emit_ConvTranspose in caffe_emitter.py
my network has deconv option.

**Comment by rainLiuplus** [comment]
Hi @Gaochunyang1314, please refer to https://github.com/microsoft/MMdnn/wiki/Contribution-Guideline 
Thanks!

**Comment by Gaochunyang1314** [comment]
@rainLiuplus Thankes!!
