### ISSUE TITLE
conversion from Caffe to Keras

### ISSUE THREAD

**Issue by liamorra** [microsoft/MMdnn#758]
Platform (like ubuntu 16.04/win10):
Ubuntu 16

Python version:
3.6.8

Source framework with version (like Tensorflow 1.4.1 with GPU):
Caffe with GPU
Destination framework with version (like CNTK 2.3 with GPU):
Keras 2.2.4
Pre-trained model path (webpath or webdisk path):
https://drive.google.com/file/d/1LTnOk4l2C60tG-eUokdeAjORxvNVaRIF/view?usp=sharing
Running scripts:

I have succesfully converted the prototxt and weights from Caffe to Keras. Unfortunately I get an error when I try to load the Keras model  (ValueError: Unknown layer: my_add), it looks like a custom layer was added during the conversion. My guess is that the Keras Add layer is not supported, is that correct?

**Comment by rainLiuplus** [comment]
Yes, you are right.  [This ](https://github.com/keras-team/keras/issues/4871)may help you load your Keras model with the customized layer. Thanks!

**Comment by liamorra** [comment]
Thanks, the solution is indeed very simple (see snippet below)

from keras.layers import Add
model =keras.models.load_model(converted_model_file, custom_objects={'my_add':Add})
