### ISSUE TITLE
stable version didn't work well

### ISSUE THREAD

**Issue by purelyvivid** [Microsoft/MMdnn#80]
Hi,
Below is my repo. I'm trying to use MMdnn to convert model from Keras to Tensorflow, and very glad you provide such a excellent tool to use. 
[https://github.com/purelyvivid/MMdnn-util](https://github.com/purelyvivid/MMdnn-util)
The problem is that when I used the, said, "stable version", it didn't work well. I got wrong massages like "inbound layer" when I tried to convert model structure to IR. Then I installed the newest version and problem solved.
Will you provide or update the stable version that can work really well? Thanks!

Platform (like ubuntu 16.04/win10): ubuntu 16.04

Python version: 2.7

Source framework with version (like Tensorflow 1.4.1 with GPU):Tensorflow 1.4 with GPU

Destination framework with version (like CNTK 2.3 with GPU):

Pre-trained model path (webpath or webdisk path):

Running scripts:

**Comment by kitstar** [comment]
Hi @purelyvivid updated. Sorry for the late response. Long vacation, Chinese Spring Festival.

```bash
pip install -U https://github.com/Microsoft/MMdnn/releases/download/0.1.3/mmdnn-0.1.3-py2.py3-none-any.whl
```
Thanks.

**Comment by kitstar** [comment]
And thanks for using our project!
