### ISSUE TITLE
tensorflow to IR transformation results in empty json and pb files

### ISSUE THREAD

**Issue by karimhasebou** [Microsoft/MMdnn#81]
Platform (like ubuntu 16.04/win10):

Python version: 3

Source framework with version: Tensorflow 1.4.1

Destination framework with version: IR format

**Comment by kitstar** [comment]
Hi @karimhasebou, could you provide your scripts and model files for reproduce? Thanks.

**Comment by karimhasebou** [comment]
@kitstar Unfortunately I cannot share the model and the related script since these are confidential.
