### ISSUE TITLE
Example to visualize mx pretrained models

### ISSUE THREAD

**Issue by shersoni610** [microsoft/MMdnn#825]
Platform (like ubuntu 16.04/win10):

Python version:

Source framework with version (like Tensorflow 1.4.1 with GPU):

Destination framework with version (like CNTK 2.3 with GPU):

Pre-trained model path (webpath or webdisk path):

Running scripts:

**Comment by linmajia** [comment]
@shersoni610 , thank you very much for the feedback. You may use [Netron](https://github.com/lutzroeder/netron) to visualize pre-trained models.
