### ISSUE TITLE
How to add a build file?

### ISSUE THREAD

**Issue by spe301** [microsoft/MMdnn#839]
Platform: win10

Python version: 3.7 (Anaconda)

Source framework: Tensorflow 2.0

Running scripts:
I tried to run `bazel build -c opt //tensorflow/contrib/android:libtensorflow_inference.so`
and I got the following error `ERROR: Skipping '//tensorflow/contrib/android:libtensorflow_inference.so': no such package 'tensorflow/contrib/android': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - C:/users/aacjp/tensorflow/tensorflow/contrib/android` I think this mean that I'm supposed to create an empty file of type file called build and put it in tensorflow/contrib/android. I am going to try this but I'm curious to see if anyone else had a similar problem and if so how they solved it.

**Comment by linmajia** [comment]
@spe301 , thank you very much for the feedback. I think you'd better ask TensorFlow developers.
