### ISSUE TITLE
Some Caffe Model URLs broken

### ISSUE THREAD

**Issue by davidturner94** [microsoft/MMdnn#840]
Platform (like ubuntu 16.04/win10):
Ubuntu 18.04

Python version:
3.7

Source framework with version (like Tensorflow 1.4.1 with GPU):
Caffe

Destination framework with version (like CNTK 2.3 with GPU):
N/A

Pre-trained model path (webpath or webdisk path):
- http://mmdnn.eastasia.cloudapp.azure.com:89/models/caffe/xception_deploy.prototxt
- http://mmdnn.eastasia.cloudapp.azure.com:89/models/caffe/xception.caffemodel

- http://mmdnn.eastasia.cloudapp.azure.com:89/models/caffe/inception-v4_deploy.prototxt
- http://mmdnn.eastasia.cloudapp.azure.com:89/models/caffe/inception-v4.caffemodel

Running scripts:
mmdownload -f caffe -n xception -o ./
mmdownload -f caffe -n inception_v4 -o ./

Error:
 urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

Any alternate links would be appreciated

**Comment by linmajia** [comment]
@davidturner94 , thank you very much for the feedback. We have closed the service. Please refer to https://github.com/BVLC/caffe/wiki/Model-Zoo and https://github.com/soeaver/caffe-model to find pre-trained Caffe models.
