### ISSUE TITLE
conver mxnet model to tensorflow, meet some errors!!!

### ISSUE THREAD

**Issue by visonpon** [microsoft/MMdnn#849]
Platform (like ubuntu 16.04/win10):
ubuntu16.04
Python version:
python3.6
Source framework with version (like Tensorflow 1.4.1 with GPU):
tensorflow1.12 mxnet.1.12,
Destination framework with version (like CNTK 2.3 with GPU):

Pre-trained model path (webpath or webdisk path):

Running scripts:
python3 -m mmdnn.conversion._scripts.convertToIR -f mxnet -n ./*.json -w ./*.params -d net --inputShape 3,224,224

error messages like follows:
segmentation fault :11
Stack trace returned 10 entries:
[bt] (0) /home/csf/anaconda3/envs/tf18/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x31f81a) [0x7f03434c581a]
....
Hope can get some help~  
thanks~

**Comment by linmajia** [comment]
@visonpon , thank you very much for the feedback. Would you please provide the complete stack traces, and your model files if possible?

**Comment by visonpon** [comment]
![trans](https://user-images.githubusercontent.com/11517731/84565305-c3d05280-ad9a-11ea-9439-fdc8056d0df5.jpg)
Above is the error message, thanks for your quick response.

**Comment by linmajia** [comment]
@visonpon , it seems to be an internal error of MXNet. Would you please provide your model files and corresponding source code?

**Comment by visonpon** [comment]
@linmajia Sorry that it's not convenient for me to upload the model and code, but I test my trained model on my current mxnet, and I also try to convert other simple mxnet models to TensorFlow, everything is normal. Only when I try to convert the new model, it fails.

**Comment by linmajia** [comment]
@visonpon , you may try a different version of MXNet (e.g., 1.2.0).
