### ISSUE TITLE
Keras to pytorch model, results are different.

### ISSUE THREAD

**Issue by leehangyu** [microsoft/MMdnn#868]
Platform (like ubuntu 16.04/win10): win10

Python version: 3.7

Source framework with version (like Tensorflow 1.4.1 with GPU): 1.15.2

Destination framework with version (like CNTK 2.3 with GPU): pytorch 1.5.1

Pre-trained model path (webpath or webdisk path): Customized model

Running scripts: 

1. mmtoir --srcFramework keras --weights mcl_1655_resnet50_edu001_ep025.h5 --network mcl_1655_resnet50.json --dstPath keras_1655_resnet50

2. mmtocode -f pytorch -n keras_1655_resnet50.pb -w keras_1655_resnet50.npy -d keras_1665_resnet50_pytorch.py -dw keras_1655.resnet50_pytorch.npy

3. mmtomodel -f pytorch -in keras_1665_resnet50_pytorch.py -iw keras_1655.resnet50_pytorch.npy -o keras_1655_resnet50_pytorch.pth

I cannot use pth model since my code 
```
torch.load("keras_1655_resnet50_pytorch.pth")
```
spits error "ModuleNotFoundError: No module named 'MainModel'"

so that I use npy and py file to inference, but results are different from what I expected.

I thought results should close enough to be reasonable, but too far from what I expected.

```
torch.return_types.sort(
values=tensor([2.3057e-22, 3.2130e-20, 3.4704e-20,  ..., 2.4499e-03, 1.1080e-02,
        9.8416e-01]),
indices=tensor([ 148, 1550,  128,  ..., 1570,  629, 1564])) torch.return_types.sort(
values=tensor([2.5458e-22, 3.5476e-20, 3.8318e-20,  ..., 2.6978e-03, 1.2086e-02,
        5.2077e-01]),
indices=tensor([ 148, 1550,  128,  ..., 1570,  629, 1564]))
```

Indices are same, but values are differenet. I udnerstand these frameworks have different shape of input tensor, but I found these are too different from other converting tools.

Please help me, why this happens. Thank you in advance

**Comment by linmajia** [comment]
@leehangyu , thank you very much for the feedback. Please refer to this [FAQ](https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/pytorch/README.md#faq) for loading the converted PyTorch model, and add the following code:
```python
import imp
MainModel = imp.load_source('MainModel', "keras_1665_resnet50_pytorch.py")
```
before
```python
torch.load("keras_1655_resnet50_pytorch.pth")
```
