### ISSUE TITLE
http://vis.mmdnn.com/ redirects to Bing

### ISSUE THREAD

**Issue by jonashaag** [microsoft/MMdnn#883]
There's a link in the README that goes to http://vis.mmdnn.com/. But that resolves to Bing...

```
$ curl -v http://vis.mmdnn.com/
*   Trying 52.164.206.56:80...
* Connected to vis.mmdnn.com (52.164.206.56) port 80 (#0)
> GET / HTTP/1.1
> Host: vis.mmdnn.com
> User-Agent: curl/7.71.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< Cache-Control: private
< Content-Type: text/html; charset=utf-8
< Location: http://www.bing.com/search?q=vis mmdnn&form=MSDTR1
< Server: Microsoft-IIS/10.0
< X-AspNet-Version: 4.0.30319
< X-Powered-By: ASP.NET
< Date: Thu, 06 Aug 2020 22:32:30 GMT
< Content-Length: 113
<


<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head><title>

</title></head>

</html>
* Connection #0 to host vis.mmdnn.com left intact
```

![grafik](https://user-images.githubusercontent.com/175722/89589387-d1a7ce80-d845-11ea-82e7-886003d676a3.png)

**Comment by JiahaoYao** [comment]
I think previous server is down and you might follow the construction [here](https://github.com/microsoft/MMdnn/tree/master/mmdnn/visualization) for the visualization though the code is old here.

**Comment by linmajia** [comment]
@jonashaag, thank you very much for the feedback. Such a server has been shut down and we will update the document.

@JiahaoYao , thank you very much for the explanation.
