### ISSUE TITLE
no npy weights file keras to pytorch

### ISSUE THREAD

**Issue by dasturge** [microsoft/MMdnn#903]
Platform (like ubuntu 16.04/win10): ubuntu 20.04
Python version: 3.6
Source framework with version (like Tensorflow 1.4.1 with GPU): keras 2.2.4, tensorflow-gpu 1.14
Destination framework with version (like CNTK 2.3 with GPU): pytorch 1.4.0
Pre-trained model path (webpath or webdisk path): model is a transfer learning resnet50
Running scripts: mmconvert -sf keras -df pytorch -in custom_resnet50.json -iw custom-resnet50-weights.h5 -om weights.pt

so the command outputs a file weights.py and weights.pt, and says something about a "b707ee71b00a45dd8d4c2fd686a7c643.npy" weights file being saved, but the weights file is not actually saved in the working directory and yet is necessary to actually load the pytorch model which is generated.

**Comment by cookieli** [comment]
Thank you for your issues. I'm sorry for repling too late. I think if mmdnn reports no errors otherwise. Then weights file should be generated correctly. Maybe you should provide more details.
