### ISSUE TITLE
Where does executables (mmdownload, mmconvert, etc..) get stored?? 

### ISSUE THREAD

**Issue by sandeepganage** [microsoft/MMdnn#911]
Platform (like ubuntu 16.04/win10): win 10

Python version: 3.7

Source framework with version (like Tensorflow 1.4.1 with GPU): tensorflow-gpu - 2.1.0

Destination framework with version (like CNTK 2.3 with GPU):

Pre-trained model path (webpath or webdisk path):

Running scripts:

I am trying to convert tensorflow model to caffe. I learnt about MMdnn just recently. 
To install mmdnn I ran : `pip install mmdnn`
But where do mmdnn's executables get stored?? I am not able to run commands like mmdownload, mmconvert etc. 
I appreciate any help on this.

**Comment by prateek9623** [comment]
If you are using Linux then those can be found in '/usr/local/bin'
