### ISSUE TITLE
when will mxnet to caffe model conversion be supported?

### ISSUE THREAD

**Issue by sunbaigui** [Microsoft/MMdnn#93]
hi, when will mxnet to caffe model conversion be supported? any timeline there?

**Comment by kitstar** [comment]
We are testing it right now. Thanks.

**Comment by kitstar** [comment]
Hi @sunbaigui . We tested the VGG19, SqueezeNet V1.1 and the inference result verifed. But there are some problem in ResNet type models. I will ping you if there is any progress. Thanks.

**Comment by sunbaigui** [comment]
hi @kitstar , I've modified some code by myself to run this through, but also encountered a problem when I try to transfer mxnet's resnet-152 model to caffe version. If you get any progress, please let me know.

**Comment by kitstar** [comment]
Hi @sunbaigui . It is done. Please check the newest code. Thanks.
