### ISSUE TITLE
Variable nodes in Tensorflow dissapears

### ISSUE THREAD

**Issue by YuriCat** [Microsoft/MMdnn#95]
I'm trying to convert Tensorflow model to Caffe model.
In procedure from Tensorflow to IR protobuf, variables nodes seemed to dissapear.

Then finally following Caffe code was generated.
'Eltwise' layer needs two input bottoms but only one were assigned,
due to no variable node had been generated in protobuf graph.

n.l1_add_2        = L.Eltwise(n.l1_add_1, operation=1, ntop=1)

Error message 

F0306 09:44:31.269845   345 layer.hpp:354] Check failed: MinBottomBlobs() <= bottom.size() (2 vs. 1) Eltwise Layer takes at least 2 bottom blob(s) as input.

I'd appreciate it if MMdnn accepts simple variable layers.

**Comment by huangxing12** [comment]
Excuse me, classmates, you solved this problem, and I just want a bottom as input for the eltwise layer sum operation.
