### ISSUE TITLE
Darknet IR support

### ISSUE THREAD

**Issue by Wheest** [Microsoft/MMdnn#99]
Saw that there is [this post](https://github.com/Microsoft/MMdnn/issues/51) references that there is no Darknet IR conversion yet.

However, are there any there are unfinished projects in the works that anyone knows of?  

Short of that, some documentation/guides on the process of converting from/to the IR itself, that I could look into?

**Comment by kitstar** [comment]
Hi @Wheest , we are understaffed to implement the Darknet part. I think I can give a guide for implementing parser/emitter. I will ping you if there is any progress. Thanks very much!

**Comment by Wheest** [comment]
Thanks @kitstar,  aye guides would be useful.  It would be unreasonable to expect core MMdnn to support every framework out of the box, but having appropriate community resources could help that goal be better realised

**Comment by namizzz** [comment]
Hi @Wheest ,please check the newest code including darknet part. Here is [readme](https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/darknet/README.md). There is also a new [wiki](https://github.com/Microsoft/MMdnn/wiki/Contribution-Guideline)about how to implement parser/emitter. Thanks!
